// <auto-generated />
namespace ARM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class univ_url_email : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(univ_url_email));
        
        string IMigrationMetadata.Id
        {
            get { return "201403292258063_univ_url_email"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
