///////////////////////////////////////////////////////////
//  ARMBaseAttribute.cs
//  Implementation of the Class ARMBaseAttribute
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:42 PM
///////////////////////////////////////////////////////////

using System;
using System.Runtime.CompilerServices;

namespace ARM.Core.Attributes
{
    /// <summary>
    ///     Постір імен що обєднує всі класи атрибутів, які використовуються в аплікації.
    ///     В нашому випадку тут розміщені базові класи атрибутів, атрибути валідації, загальні атрибути для моделей даних.
    /// </summary>
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }

    /// <summary>
    ///     Базовий класс для атрибутів.
    /// </summary>
    public abstract class ARMBaseAttribute : Attribute
    {
    } //end ARMBaseAttribute
} //end namespace Attributes