///////////////////////////////////////////////////////////
//  ARMMaxAttribute.cs
//  Implementation of the Class ARMMaxAttribute
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:42 PM
///////////////////////////////////////////////////////////




using ARM.Core.Attributes;
namespace ARM.Core.Attributes {
	public class ARMMaxAttribute : ARMNumericAttribute {

		public ARMMaxAttribute(){

		}

		~ARMMaxAttribute(){

		}

	}//end ARMMaxAttribute

}//end namespace Attributes