///////////////////////////////////////////////////////////
//  ARMMinAttribute.cs
//  Implementation of the Class ARMMinAttribute
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:42 PM
///////////////////////////////////////////////////////////

namespace ARM.Core.Attributes
{
    /// <summary>
    ///     атрибут, що вказує на валідація властивості по мінімальному значенню
    /// </summary>
    public class ARMMinAttribute : ARMNumericAttribute
    {
        ~ARMMinAttribute()
        {
        }
    } //end ARMMinAttribute
} //end namespace Attributes 