///////////////////////////////////////////////////////////
//  ARMPhoneAttribute.cs
//  Implementation of the Class ARMPhoneAttribute
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:43 PM
///////////////////////////////////////////////////////////

namespace ARM.Core.Attributes
{
    /// <summary>
    ///     атрибут, що вказує на валідацію властивості щодо встановленого шаблону телефону
    /// </summary>
    public class ARMPhoneAttribute : ARMStringAttribute
    {
        ~ARMPhoneAttribute()
        {
        }
    } //end ARMPhoneAttribute
} //end namespace Attributes