///////////////////////////////////////////////////////////
//  ARMRangeAttribute.cs
//  Implementation of the Class ARMRangeAttribute
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:43 PM
///////////////////////////////////////////////////////////

namespace ARM.Core.Attributes
{
    /// <summary>
    ///     атрибут, який вказує на валідацію властивості у відповідності до діапазону
    /// </summary>
    public class ARMRangeAttribute : ARMNumericAttribute
    {
        ~ARMRangeAttribute()
        {
        }
    } //end ARMRangeAttribute
} //end namespace Attributes