///////////////////////////////////////////////////////////
//  ARMRangeAttribute.cs
//  Implementation of the Class ARMRangeAttribute
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:43 PM
///////////////////////////////////////////////////////////

namespace ARM.Core.Attributes
{
    public class ARMRangeAttribute : ARMNumericAttribute
    {
        public ARMRangeAttribute()
        {
        }

        ~ARMRangeAttribute()
        {
        }
    }//end ARMRangeAttribute
}//end namespace Attributes