///////////////////////////////////////////////////////////
//  ARMUrlAttribute.cs
//  Implementation of the Class ARMUrlAttribute
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:43 PM
///////////////////////////////////////////////////////////

namespace ARM.Core.Attributes
{
    /// <summary>
    /// атрибут, який вказує на валідацію властивості, як URL посилання
    /// </summary>
    public class ARMUrlAttribute : ARMStringAttribute
    {
        public ARMUrlAttribute()
        {
        }

        ~ARMUrlAttribute()
        {
        }
    }//end ARMUrlAttribute
}//end namespace Attributes