///////////////////////////////////////////////////////////
//  ARMValidationAttribute.cs
//  Implementation of the Class ARMValidationAttribute
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:43 PM
///////////////////////////////////////////////////////////

using ARM.Core.Interfaces;

namespace ARM.Core.Attributes
{
    /// <summary>
    /// базовий класс для всіх атрибутів валідації
    /// </summary>
    public class ARMValidationAttribute : ARMBaseAttribute, IARMValidationAttribute
    {
        public ARMValidationAttribute()
        {
        }

        ~ARMValidationAttribute()
        {
        }
    }//end ARMValidationAttribute
}//end namespace Attributes