///////////////////////////////////////////////////////////
//  ARMMainStatusBasrViewModel.cs
//  Implementation of the Class ARMMainStatusBasrViewModel
//  Generated by Enterprise Architect
//  Created on:      02-Apr-2014 1:17:47 AM
///////////////////////////////////////////////////////////

using ARM.Core.MVVM;
using ARM.Module.Interfaces;
using ARM.Module.Interfaces.View;

namespace ARM.Module.ViewModel.Main
{
    public class ARMMainStatusBarViewModel : ARMViewModelBase, IARMMainStatusBarViewModel
    {
        public ARMMainStatusBarViewModel(IARMMainStatusBarView statusBarView)
            : base(statusBarView)
        {
        }
    }//end ARMMainStatusBasrViewModel
}//end namespace Main