///////////////////////////////////////////////////////////
//  ARMMainToolboxViewModel.cs
//  Implementation of the Class ARMMainToolboxViewModel
//  Generated by Enterprise Architect
//  Created on:      02-Apr-2014 1:17:47 AM
///////////////////////////////////////////////////////////

using System.Collections.ObjectModel;
using ARM.Core.MVVM;
using ARM.Module.Interfaces;
using ARM.Module.Interfaces.View;

namespace ARM.Module.ViewModel.Main
{
    public class ARMMainToolboxViewModel : ARMViewModelBase, IARMMainToolboxViewModel
    {
        public ARMMainToolboxViewModel(IARMMainToolboxView toolboxView) 
            : base(toolboxView)
        {
        }

        public ObservableCollection<IARMMainToolboxCommand> Commands { get; private set; }
    }//end ARMMainToolboxViewModel
}//end namespace Main