///////////////////////////////////////////////////////////
//  ARMMainMenuViewModel.cs
//  Implementation of the Class ARMMainMenuViewModel
//  Generated by Enterprise Architect
//  Created on:      02-Apr-2014 1:17:47 AM
///////////////////////////////////////////////////////////

using System.Collections.ObjectModel;
using System.ComponentModel;
using ARM.Core.Interfaces;
using ARM.Core.MVVM;
using ARM.Module.Interfaces;
using ARM.Module.Interfaces.View;

namespace ARM.Module.ViewModel.Main
{
    public class ARMMainMenuViewModel : ARMViewModelBase, IARMMainMenuViewModel
    {
        public ARMMainMenuViewModel(IARMMainMenuView menuView ) : base(menuView)
        {
        }

        public ObservableCollection<IARMMenuCommand> Files { get; private set; }
        public ObservableCollection<IARMMenuCommand> Documents { get; private set; }
        public ObservableCollection<IARMMenuCommand> References { get; private set; }
        public ObservableCollection<IARMMenuCommand> Reports { get; private set; }
        public ObservableCollection<IARMMenuCommand> Services { get; private set; }
        public ObservableCollection<IARMMenuCommand> Helps { get; private set; }
    }//end ARMMainMenuViewModel
}//end namespace Main