///////////////////////////////////////////////////////////
//  PaymentDal.cs
//  Implementation of the Class PaymentDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:44 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Payment;
namespace ARM.Data.Implementation.Payment {
    public class PaymentDal : BaseDal<Models.Payment>, IPaymentDal
    {

		

	}//end PaymentDal

}//end namespace Payment