///////////////////////////////////////////////////////////
//  PaymentDal.cs
//  Implementation of the Class PaymentDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:44 PM
///////////////////////////////////////////////////////////

using ARM.Data.Interfaces.Payment;
using ARM.Data.Layer.Context;
using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Implementation.Payment
{
    /// <summary>
    /// Реалізація доступу до даних для платежів
    /// </summary>
    public class PaymentDal : BaseDal<Models.Payment>, IPaymentDal
    {
        public PaymentDal(IContext<Models.Payment> context)
            : base(context)
        {
        }
    } //end PaymentDal
} //end namespace Payment