///////////////////////////////////////////////////////////
//  ILanguageDal.cs
//  Implementation of the Interface ILanguageDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:42 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Language
{
    /// <summary>
    /// Інтерфейс доступу до даних мов
    /// </summary>
    public interface ILanguageDal : IDal<Models.Language>
    {
    } //end ILanguageDal
} //end namespace Language