///////////////////////////////////////////////////////////
//  ILanguageContext.cs
//  Implementation of the Interface ILanguageContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:41 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Language
{
    /// <summary>
    /// Інтерфейс контексту для роботи з мовами
    /// </summary>
    public interface ILanguageContext : IContext<Models.Language>
    {
    } //end ILanguageContext
} //end namespace Language