///////////////////////////////////////////////////////////
//  ARMValidationResult.cs
//  Implementation of the Class ARMValidationResult
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using ARM.Core.Interfaces;
namespace ARM.Core.Validation {
	public class ARMValidationResult : IARMValidationResult {

		public ARMValidationResult(){

		}

		~ARMValidationResult(){

		}

		public bool IsValid{
			get;
			set;
		}

		public IEnumerable<string> GetErrors(){

			return null;
		}

	}//end ARMValidationResult

}//end namespace Validation