///////////////////////////////////////////////////////////
//  ARMValidationResult.cs
//  Implementation of the Class ARMValidationResult
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using System.Linq;
using ARM.Core.Interfaces;

namespace ARM.Core.Validation
{
    public class ARMValidationResult : IARMValidationResult
    {
        private readonly IList<string> _listMessage = new List<string>();


        public void AddMessage(string mes)
        {
            _listMessage.Add(mes);
        }

        public void ClearMessages()
        {
            _listMessage.Clear();
        }

        public bool IsValid
        {
            get;
            set;
        }

        public IEnumerable<string> GetErrors()
        {
            return _listMessage.AsEnumerable();
        }
    }//end ARMValidationResult
}//end namespace Validation