///////////////////////////////////////////////////////////
//  IMarkDal.cs
//  Implementation of the Interface IMarkDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:42 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Mark
{
    public interface IMarkDal : IDal<Models.Mark>
    {
    }//end IMarkDal
}//end namespace Mark