///////////////////////////////////////////////////////////
//  MarkDal.cs
//  Implementation of the Class MarkDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:43 PM
///////////////////////////////////////////////////////////

using ARM.Data.Interfaces.Mark;
using ARM.Data.Layer.Context;
using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Implementation.Mark
{
    /// <summary>
    /// Реалізація доступу до даних для оцінок
    /// </summary>
    public class MarkDal : BaseDal<Models.Mark>, IMarkDal
    {
        /// <summary>
        /// Створити екземпляр <see cref="MarkDal"/> class.
        /// </summary>
        /// <param name="context">The context.</param>
        public MarkDal(IContext<Models.Mark> context)
            : base(context)
        {
        }
    } //end MarkDal
} //end namespace Mark