///////////////////////////////////////////////////////////
//  MarkContext.cs
//  Implementation of the Class MarkContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:43 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Mark;
namespace ARM.Data.Implementation.Mark {
    public class MarkContext : BaseContext<Models.Mark>, IMarkContext
    {


	}//end MarkContext

}//end namespace Mark