///////////////////////////////////////////////////////////
//  ClassContext.cs
//  Implementation of the Class ClassContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:38 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Class;
namespace ARM.Data.Implementation.Class {
    public class ClassContext : BaseContext<Models.Class>, IClassContext
    {

		

	}//end ClassContext

}//end namespace Class