///////////////////////////////////////////////////////////
//  ClassBll.cs
//  Implementation of the Class ClassBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:38 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Class;
namespace ARM.Data.Implementation.Class {
    public class ClassBll : BaseBll<Models.Class>, IClassBll
    {


	}//end ClassBll

}//end namespace Class