///////////////////////////////////////////////////////////
//  LogLevel.cs
//  Implementation of the Class LogLevel
//  Generated by Enterprise Architect
//  Created on:      30-Mar-2014 8:12:16 PM
///////////////////////////////////////////////////////////

namespace ARM.Infrastructure.Enums
{
    /// <summary>
    /// Простір імен основних типів перечислень.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal class NamespaceDoc
    {
    }

    /// <summary>
    /// тип для позначення обєкту логування
    /// </summary>
    public enum eARMLogLevel : int
    {
        None,
        Warning,
        Info,
        Error
    }//end LogLevel
}//end namespace Enums