namespace ARM.Core.Enums
{
    public enum eARMMetadata
    {
        None,
        Achivement,
        Address,
        Class,
        Contract,
        Country,
        Faculty,
        Group,
        Hobby,
        Invoice,
        Language,
        Mark,
        Parent,
        Payment,
        Session,
        Settings,
        Specialty,
        Staff,
        Student,
        University,
        User,
        Employer,
        Visa,
        Login
    }
}