///////////////////////////////////////////////////////////
//  ViewMode.cs
//  Implementation of the Class ViewMode
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////

namespace ARM.Core.Enums
{
    /// <summary>
    /// тип режиму роботи користувацього інтерфейсу.
    /// У відповідності до цього типу змінюється логіка роботи програми.
    /// </summary>
    public enum ViewMode : int
    {
        None,
        Add,
        Edit,
        View
    }//end ViewMode
}//end namespace Enums