///////////////////////////////////////////////////////////
//  IBll.cs
//  Implementation of the Interface IBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:40 PM
///////////////////////////////////////////////////////////


using System.Collections.Generic;

namespace ARM.Data.Layer.Interfaces {
	public interface IBll<T>  {

		/// 
		/// <param name="obj"></param>
		void Insert(T obj);

		/// 
		/// <param name="list"></param>
		void InsertAll(IEnumerable<T> list);

		/// 
		/// <param name="obj"></param>
		void Update(T obj);

		/// 
		/// <param name="id"></param>
		void Delete(long id);

		/// 
		/// <param name="id"></param>
		T GetById(long id);

		IEnumerable<T> GetAll();
	}//end IBll

}//end namespace Interfaces