///////////////////////////////////////////////////////////
//  IContext.cs
//  Implementation of the Interface IContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:41 PM
///////////////////////////////////////////////////////////

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using ARM.Data.Models;

namespace ARM.Data.Layer.Interfaces
{
    public interface IContext<T> : IDisposable where T : class
    {
        IDbSet<T> GetItems();

        void Save();

        void Update(T obj);

        void Refresh();

        DbEntityEntry<T> Entry(T e);

        DbSet<TObj> Set<TObj>() where TObj : BaseModel;
    }//end IContext
}//end namespace Interfaces