///////////////////////////////////////////////////////////
//  IDal.cs
//  Implementation of the Interface IDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:41 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace ARM.Data.Layer.Interfaces
{
    public interface IDal<T> : IDisposable
    {
        ///
        /// <param name="obj"></param>
        void Insert(T obj);

        void InsertAll(IEnumerable<T> list);

        ///
        /// <param name="obj"></param>
        void Update(T obj);

        ///
        /// <param name="obj"></param>
        void Delete(T obj);

        IEnumerable<T> GetAll();

        ///
        /// <param name="id"></param>
        T GetById(Guid id);

        void Save();

        void Refresh();

        IEnumerable<T> GetAllWithRelated();

        IEnumerable<T> GetAll(Func<T, bool> filter);
        IEnumerable<T> GetAll(Expression<Func<T, bool>> filter);
    }//end IDal
}//end namespace Interfaces