///////////////////////////////////////////////////////////
//  IDal.cs
//  Implementation of the Interface IDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:41 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

namespace ARM.Data.Layer.Interfaces
{
    /// <summary>
    /// Інтерфейс доступу до даних
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public interface IDal<T> : IDisposable
    {
        /// <summary>
        /// додає новий обєкт в БД.
        /// </summary>
        /// <param name="obj">Обєкт.</param>
        void Insert(T obj);

        /// <summary>
        /// Додає список обєктів в БД.
        /// </summary>
        /// <param name="list">Список.</param>
        void InsertAll(IEnumerable<T> list);

        /// <summary>
        /// Обновлює обєкт в БД.
        /// </summary>
        /// <param name="obj">Обєкт.</param>
        void Update(T obj);

        /// <summary>
        /// Видаляє обраний обєкт з БД.
        /// </summary>
        /// <param name="obj">Обєкт.</param>
        void Delete(T obj);

        /// <summary>
        /// Повертає всі записи.
        /// </summary>
        /// <returns></returns>
        IEnumerable<T> GetAll();

        /// <summary>
        /// Поветрає обєкт за його ідентифікатором.
        /// </summary>
        /// <param name="id">Ідентифікатор.</param>
        /// <returns></returns>
        T GetById(Guid id);

        /// <summary>
        /// Зберігає зміни в БД.
        /// </summary>
        void Save();

        /// <summary>
        /// Оновлення даних з БД.
        /// </summary>
        void Refresh();

        /// <summary>
        /// Отримує всі обєкти разом з їх залежними записами.
        /// </summary>
        /// <returns></returns>
        IEnumerable<T> GetAllWithRelated();

        /// <summary>
        /// Повертає записи у відповідності до фільтру.
        /// </summary>
        /// <param name="filter">Фільтр.</param>
        /// <returns></returns>
        IEnumerable<T> GetAll(Func<T, bool> filter);

        /// <summary>
        /// Повертає всі записи у відповідності до виразу.
        /// </summary>
        /// <param name="filter">Вираз.</param>
        /// <returns></returns>
        IEnumerable<T> GetAll(Expression<Func<T, bool>> filter);

        /// <summary>
        /// Повертає обєкт запиту.
        /// </summary>
        /// <returns></returns>
        IQueryable<T> GetAsQueryable();


    } //end IDal
} //end namespace Interfaces