///////////////////////////////////////////////////////////
//  IHobbyBll.cs
//  Implementation of the Interface IHobbyBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:41 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Hobby
{
    /// <summary>
    /// Простір імен інтерфейсів для моделей даних - хобі
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal class NamespaceDoc
    {
    }
    /// <summary>
    /// Інтерфейс бізнес логіки хобі
    /// </summary>
    public interface IHobbyBll : IBll<Models.Hobby>
    {
    } //end IHobbyBll
} //end namespace Hobby