///////////////////////////////////////////////////////////
//  IHobbyDal.cs
//  Implementation of the Interface IHobbyDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:41 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Hobby
{
    public interface IHobbyDal : IDal<Models.Hobby>
    {
    }//end IHobbyDal
}//end namespace Hobby