///////////////////////////////////////////////////////////
//  IUniversityBll.cs
//  Implementation of the Interface IUniversityBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:43 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.University
{
    /// <summary>
    /// Простір імен інтерфейсів для моделей даних - університети
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal class NamespaceDoc
    {
    }

    /// <summary>
    /// Інтерфейс бізнес логіки університету
    /// </summary>
    public interface IUniversityBll : IBll<Models.University>
    {
    } //end IUniversityBll
} //end namespace University