///////////////////////////////////////////////////////////
//  ARMViewModelBase.cs
//  Implementation of the Class ARMViewModelBase
//  Generated by Enterprise Architect
//  Created on:      30-Mar-2014 6:35:57 PM
///////////////////////////////////////////////////////////

using System;
using System.ComponentModel;
using System.Linq.Expressions;
using ARM.Core.Interfaces;

namespace ARM.Core.MVVM
{
    public abstract class ARMViewModelBase : IARMViewModel
    {
        ///
        /// <param name="view"></param>
        protected ARMViewModelBase(IARMView view)
        {
            View = view;
        }

        public event PropertyChangedEventHandler PropertyChanged;

        ///
        /// <param name="propertyName"></param>
        protected void OnPropertyChanged(string propertyName)
        {
        }

        ///
        /// <param name="exp"></param>
        protected void OnPropertyChanged<T>(Expression<Func<T>> exp)
        {
        }

        public IARMView View
        {
            get;
            protected set;
        }
    }//end ARMViewModelBase
}//end namespace MVVM