///////////////////////////////////////////////////////////
//  IARMModel.cs
//  Implementation of the Interface IARMModel
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////




namespace ARM.Core.Interfaces.Data {
	public interface IARMModel  {

	}//end IARMModel

}//end namespace Data