///////////////////////////////////////////////////////////
//  StudentContext.cs
//  Implementation of the Class StudentContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:46 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Student;
namespace ARM.Data.Implementation.Student {
    public class StudentContext : BaseContext<Models.Student>, IStudentContext
    {


	}//end StudentContext

}//end namespace Student