///////////////////////////////////////////////////////////
//  StudentDal.cs
//  Implementation of the Class StudentDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:46 PM
///////////////////////////////////////////////////////////

using ARM.Data.Interfaces.Student;
using ARM.Data.Layer.Context;
using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Implementation.Student
{
    /// <summary>
    /// Реалізація доступу до даних для студентів
    /// </summary>
    public class StudentDal : BaseDal<Models.Student>, IStudentDal
    {
        public StudentDal(IContext<Models.Student> context)
            : base(context)
        {
        }

        protected override void DeleteAddInfo(Models.Student entity)
        {
            base.DeleteAddInfo(entity);
            Context.Entry(entity).Collection(e => e.Languages).Load();
            Context.Entry(entity).Collection(e => e.Hobbies).Load();
            Context.Entry(entity).Collection(e => e.Achivements).Load();
            Context.Entry(entity).Collection(e => e.Visas).Load();
            var ctx = Context as StudentContext;
            ctx.Hobbies.RemoveRange(entity.Hobbies);
            ctx.Achivements.RemoveRange(entity.Achivements);
            ctx.Visas.RemoveRange(entity.Visas);
            entity.Languages.Clear();
        }
    } //end StudentDal
} //end namespace Student