///////////////////////////////////////////////////////////
//  StudentBll.cs
//  Implementation of the Class StudentBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:46 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Linq;
using ARM.Data.Interfaces.Student;
using ARM.Data.Layer.Context;
using ARM.Data.Layer.Interfaces;
using ARM.Data.Models;

namespace ARM.Data.Implementation.Student
{
    /// <summary>
    /// Простір імен для реалізації функциональності по роботі з - студентами
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal class NamespaceDoc
    {
    }

    /// <summary>
    /// Реалізація бізнес логіки для студентів
    /// </summary>
    public class StudentBll : BaseBll<Models.Student>, IStudentBll
    {
        public StudentBll(IDal<Models.Student> dal)
            : base(dal)
        {
        }

        /// <summary>
        /// Отримує всіх студентів-іноземців.
        /// </summary>
        /// <returns></returns>
        public IEnumerable<Models.Student> GetAllForeignStudent()
        {
            return Dal.GetAsQueryable().Where(s => s.IsForeign);
        }

        /// <summary>
        /// Повернути всых студентів, які пішли на перездачу.
        /// </summary>
        /// <param name="listGroups">Список груп.</param>
        /// <returns></returns>
        public IEnumerable<Models.Student> GetAllRenewStudentInGroups(IEnumerable<Guid> listGroups)
        {
            return Dal.GetAsQueryable().Where(s => listGroups.Contains(s.GroupId.Value) && s.Status == StudentStatus.Renewed);
        }
    } //end StudentBll
} //end namespace Student