///////////////////////////////////////////////////////////
//  SpecialtyContext.cs
//  Implementation of the Class SpecialtyContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:45 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Specialty;
namespace ARM.Data.Implementation.Specialty {
    public class SpecialtyContext : BaseContext<Models.Specialty>, ISpecialtyContext
    {


	}//end SpecialtyContext

}//end namespace Specialty