///////////////////////////////////////////////////////////
//  SpecialtyBll.cs
//  Implementation of the Class SpecialtyBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:45 PM
///////////////////////////////////////////////////////////

using ARM.Data.Interfaces.Specialty;
using ARM.Data.Layer.Context;
using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Implementation.Specialty
{

    /// <summary>
    /// Простір імен для реалізації функциональності по роботі з - спеціальностями
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal class NamespaceDoc
    {
    }

    /// <summary>
    /// Реалізація бізнес логіки для спецальностей
    /// </summary>
    public class SpecialtyBll : BaseBll<Models.Specialty>, ISpecialtyBll
    {
        /// <summary>
        /// Створити екземпляр <see cref="SpecialtyBll"/> class.
        /// </summary>
        /// <param name="dal">The dal.</param>
        public SpecialtyBll(IDal<Models.Specialty> dal)
            : base(dal)
        {
        }
    } //end SpecialtyBll
} //end namespace Specialty