///////////////////////////////////////////////////////////
//  IStaffContext.cs
//  Implementation of the Interface IStaffContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:43 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Staff
{
    /// <summary>
    /// Інтерфейс контексту для роботи з працівниками
    /// </summary>
    public interface IStaffContext : IContext<Models.Staff>
    {
    } //end IStaffContext
} //end namespace Staff