///////////////////////////////////////////////////////////
//  IStaffBll.cs
//  Implementation of the Interface IStaffBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:43 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Staff
{
    /// <summary>
    /// Простір імен інтерфейсів для моделей даних - персонал
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal class NamespaceDoc
    {
    }

    /// <summary>
    /// Інтерфейс бізнес логіки працівників
    /// </summary>
    public interface IStaffBll : IBll<Models.Staff>
    {
    } //end IStaffBll
} //end namespace Staff