///////////////////////////////////////////////////////////
//  LanguageDal.cs
//  Implementation of the Class LanguageDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:43 PM
///////////////////////////////////////////////////////////

using ARM.Data.Interfaces.Language;
using ARM.Data.Layer.Context;
using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Implementation.Language
{
    public class LanguageDal : BaseDal<Models.Language>, ILanguageDal
    {
        public LanguageDal(IContext<Models.Language> context)
            : base(context)
        {
        }
    }//end LanguageDal
}//end namespace Language