///////////////////////////////////////////////////////////
//  LanguageContext.cs
//  Implementation of the Class LanguageContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:43 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Language;
namespace ARM.Data.Implementation.Language {
    public class LanguageContext : BaseContext<Models.Language>, ILanguageContext
    {


	}//end LanguageContext

}//end namespace Language