///////////////////////////////////////////////////////////
//  IPaymentDal.cs
//  Implementation of the Interface IPaymentDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:42 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Payment
{
    /// <summary>
    /// Інтерфейс доступу до даних платіжок
    /// </summary>
    public interface IPaymentDal : IDal<Models.Payment>
    {
    } //end IPaymentDal
} //end namespace Payment