///////////////////////////////////////////////////////////
//  IPaymentContext.cs
//  Implementation of the Interface IPaymentContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:42 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Payment
{
    /// <summary>
    /// Інтерфейс контексту для роботи з платіжками
    /// </summary>
    public interface IPaymentContext : IContext<Models.Payment>
    {
    } //end IPaymentContext
} //end namespace Payment