///////////////////////////////////////////////////////////
//  IInvoiceBll.cs
//  Implementation of the Interface IInvoiceBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:41 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Invoice
{
    /// <summary>
    /// Простір імен інтерфейсів для моделей даних - рахунками
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal class NamespaceDoc
    {
    }
    /// <summary>
    /// Інтерфейс бізнес логіки рахунків
    /// </summary>
    public interface IInvoiceBll : IBll<Models.Invoice>
    {
        IEnumerable<Models.Invoice> GetInvoicesByContractAndPeriod(Guid idContract, DateTime begin, DateTime end);
    } //end IInvoiceBll
} //end namespace Invoice