///////////////////////////////////////////////////////////
//  IInvoiceDal.cs
//  Implementation of the Interface IInvoiceDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:41 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Invoice
{
    public interface IInvoiceDal : IDal<Models.Invoice>
    {
    } //end IInvoiceDal
} //end namespace Invoice