//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM.Resource.AppResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARM.Resource.AppResource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        public static string Button_SetPassword {
            get {
                return ResourceManager.GetString("Button_SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelour.
        /// </summary>
        public static string Enum_Bachelour {
            get {
                return ResourceManager.GetString("Enum_Bachelour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Enum_Distance {
            get {
                return ResourceManager.GetString("Enum_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Enum_English {
            get {
                return ResourceManager.GetString("Enum_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expelled.
        /// </summary>
        public static string Enum_Expelled {
            get {
                return ResourceManager.GetString("Enum_Expelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Enum_Female {
            get {
                return ResourceManager.GetString("Enum_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullTime.
        /// </summary>
        public static string Enum_FullTime {
            get {
                return ResourceManager.GetString("Enum_FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduated.
        /// </summary>
        public static string Enum_Graduated {
            get {
                return ResourceManager.GetString("Enum_Graduated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture.
        /// </summary>
        public static string Enum_Lecture {
            get {
                return ResourceManager.GetString("Enum_Lecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Enum_Male {
            get {
                return ResourceManager.GetString("Enum_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string Enum_Master {
            get {
                return ResourceManager.GetString("Enum_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Enum_New {
            get {
                return ResourceManager.GetString("Enum_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_None {
            get {
                return ResourceManager.GetString("Enum_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaidUp.
        /// </summary>
        public static string Enum_PaidUp {
            get {
                return ResourceManager.GetString("Enum_PaidUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phd.
        /// </summary>
        public static string Enum_Phd {
            get {
                return ResourceManager.GetString("Enum_Phd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialist.
        /// </summary>
        public static string Enum_Specialist {
            get {
                return ResourceManager.GetString("Enum_Specialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studies.
        /// </summary>
        public static string Enum_Studies {
            get {
                return ResourceManager.GetString("Enum_Studies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string Enum_Technician {
            get {
                return ResourceManager.GetString("Enum_Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string Enum_Ukrainian {
            get {
                return ResourceManager.GetString("Enum_Ukrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Grid_Country_Title {
            get {
                return ResourceManager.GetString("Grid_Country_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Grid_Language_Title {
            get {
                return ResourceManager.GetString("Grid_Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Grid_Staff_Title {
            get {
                return ResourceManager.GetString("Grid_Staff_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universities.
        /// </summary>
        public static string Grid_University_Title {
            get {
                return ResourceManager.GetString("Grid_University_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM - bla - bla.
        /// </summary>
        public static string MAINWINDOW_TITLE {
            get {
                return ResourceManager.GetString("MAINWINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string MENU_DOCUMENTS_TITLE {
            get {
                return ResourceManager.GetString("MENU_DOCUMENTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MENU_FILE_TITLE {
            get {
                return ResourceManager.GetString("MENU_FILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MENU_HELP_TITLE {
            get {
                return ResourceManager.GetString("MENU_HELP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string MENU_REFERENCES_TITLE {
            get {
                return ResourceManager.GetString("MENU_REFERENCES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string MENU_REPORTS_TITLE {
            get {
                return ResourceManager.GetString("MENU_REPORTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string MENU_SERVICES_TITLE {
            get {
                return ResourceManager.GetString("MENU_SERVICES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universities.
        /// </summary>
        public static string Menu_University {
            get {
                return ResourceManager.GetString("Menu_University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Message_ErrorCaprion {
            get {
                return ResourceManager.GetString("Message_ErrorCaprion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Message_InformationCaption {
            get {
                return ResourceManager.GetString("Message_InformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Message_QuestionCaption {
            get {
                return ResourceManager.GetString("Message_QuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        public static string Message_Save {
            get {
                return ResourceManager.GetString("Message_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Message_WarningCaption {
            get {
                return ResourceManager.GetString("Message_WarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Model_Action_Add {
            get {
                return ResourceManager.GetString("Model_Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Model_Action_Edit {
            get {
                return ResourceManager.GetString("Model_Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Model_Action_View {
            get {
                return ResourceManager.GetString("Model_Action_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        public static string Model_Address_Apartment {
            get {
                return ResourceManager.GetString("Model_Address_Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Model_Address_City {
            get {
                return ResourceManager.GetString("Model_Address_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Model_Address_Country {
            get {
                return ResourceManager.GetString("Model_Address_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        public static string Model_Address_House {
            get {
                return ResourceManager.GetString("Model_Address_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Model_Address_Region {
            get {
                return ResourceManager.GetString("Model_Address_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Model_Address_Street {
            get {
                return ResourceManager.GetString("Model_Address_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addresses.
        /// </summary>
        public static string Model_Address_Title {
            get {
                return ResourceManager.GetString("Model_Address_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},r. {1}, s. {2}, st. {3}, h. {4}, a. {5}.
        /// </summary>
        public static string Model_Address_ToString {
            get {
                return ResourceManager.GetString("Model_Address_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string Model_Class_Session {
            get {
                return ResourceManager.GetString("Model_Class_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecturer.
        /// </summary>
        public static string Model_Class_Staff {
            get {
                return ResourceManager.GetString("Model_Class_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classes.
        /// </summary>
        public static string Model_Class_Title {
            get {
                return ResourceManager.GetString("Model_Class_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Address.
        /// </summary>
        public static string Model_Data_Address {
            get {
                return ResourceManager.GetString("Model_Data_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Class.
        /// </summary>
        public static string Model_Data_Class {
            get {
                return ResourceManager.GetString("Model_Data_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Country.
        /// </summary>
        public static string Model_Data_Country {
            get {
                return ResourceManager.GetString("Model_Data_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Faculty.
        /// </summary>
        public static string Model_Data_Faculty {
            get {
                return ResourceManager.GetString("Model_Data_Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Group.
        /// </summary>
        public static string Model_Data_Group {
            get {
                return ResourceManager.GetString("Model_Data_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Language.
        /// </summary>
        public static string Model_Data_Language {
            get {
                return ResourceManager.GetString("Model_Data_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Parent.
        /// </summary>
        public static string Model_Data_Parent {
            get {
                return ResourceManager.GetString("Model_Data_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Session.
        /// </summary>
        public static string Model_Data_Session {
            get {
                return ResourceManager.GetString("Model_Data_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Speciality.
        /// </summary>
        public static string Model_Data_Speciality {
            get {
                return ResourceManager.GetString("Model_Data_Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Staff.
        /// </summary>
        public static string Model_Data_Staff {
            get {
                return ResourceManager.GetString("Model_Data_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Student.
        /// </summary>
        public static string Model_Data_Student {
            get {
                return ResourceManager.GetString("Model_Data_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} University.
        /// </summary>
        public static string Model_Data_University {
            get {
                return ResourceManager.GetString("Model_Data_University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} User.
        /// </summary>
        public static string Model_Data_User {
            get {
                return ResourceManager.GetString("Model_Data_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        public static string Model_DateModified {
            get {
                return ResourceManager.GetString("Model_DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string Model_Faculty_Head {
            get {
                return ResourceManager.GetString("Model_Faculty_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculties.
        /// </summary>
        public static string Model_Faculty_Title {
            get {
                return ResourceManager.GetString("Model_Faculty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string Model_Faculty_University {
            get {
                return ResourceManager.GetString("Model_Faculty_University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curator.
        /// </summary>
        public static string Model_Group_Curator {
            get {
                return ResourceManager.GetString("Model_Group_Curator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string Model_Group_Faculty {
            get {
                return ResourceManager.GetString("Model_Group_Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Model_Group_Title {
            get {
                return ResourceManager.GetString("Model_Group_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Model_Name {
            get {
                return ResourceManager.GetString("Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Model_Parent_Address {
            get {
                return ResourceManager.GetString("Model_Parent_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Model_Parent_Student {
            get {
                return ResourceManager.GetString("Model_Parent_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents.
        /// </summary>
        public static string Model_Parent_Title {
            get {
                return ResourceManager.GetString("Model_Parent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Model_Person_Email {
            get {
                return ResourceManager.GetString("Model_Person_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Model_Person_FirstName {
            get {
                return ResourceManager.GetString("Model_Person_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Model_Person_LastName {
            get {
                return ResourceManager.GetString("Model_Person_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string Model_Person_MiddleName {
            get {
                return ResourceManager.GetString("Model_Person_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home phone.
        /// </summary>
        public static string Model_Person_PhoneHome {
            get {
                return ResourceManager.GetString("Model_Person_PhoneHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone.
        /// </summary>
        public static string Model_Person_PhoneMobile {
            get {
                return ResourceManager.GetString("Model_Person_PhoneMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Model_Person_Sex {
            get {
                return ResourceManager.GetString("Model_Person_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rector.
        /// </summary>
        public static string Model_Rector {
            get {
                return ResourceManager.GetString("Model_Rector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin date.
        /// </summary>
        public static string Model_Session_DateBegin {
            get {
                return ResourceManager.GetString("Model_Session_DateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string Model_Session_DateEnd {
            get {
                return ResourceManager.GetString("Model_Session_DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string Model_Session_Title {
            get {
                return ResourceManager.GetString("Model_Session_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Base stipend.
        /// </summary>
        public static string Model_Settings_DefBaseStipend {
            get {
                return ResourceManager.GetString("Model_Settings_DefBaseStipend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Country.
        /// </summary>
        public static string Model_Settings_DefCountry {
            get {
                return ResourceManager.GetString("Model_Settings_DefCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Education level.
        /// </summary>
        public static string Model_Settings_DefEducationLevel {
            get {
                return ResourceManager.GetString("Model_Settings_DefEducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Increased stipend.
        /// </summary>
        public static string Model_Settings_DefIncreaseStipend {
            get {
                return ResourceManager.GetString("Model_Settings_DefIncreaseStipend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defautl Invouce status.
        /// </summary>
        public static string Model_Settings_DefInvoiceStatus {
            get {
                return ResourceManager.GetString("Model_Settings_DefInvoiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Stipend mark.
        /// </summary>
        public static string Model_Settings_DefStipendMark {
            get {
                return ResourceManager.GetString("Model_Settings_DefStipendMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Stipend high mark.
        /// </summary>
        public static string Model_Settings_DefStipenHighMark {
            get {
                return ResourceManager.GetString("Model_Settings_DefStipenHighMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default University.
        /// </summary>
        public static string Model_Settings_DefUniversity {
            get {
                return ResourceManager.GetString("Model_Settings_DefUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Settings.
        /// </summary>
        public static string Model_Settings_Title {
            get {
                return ResourceManager.GetString("Model_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string Model_Speciality_Faculty {
            get {
                return ResourceManager.GetString("Model_Speciality_Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialities.
        /// </summary>
        public static string Model_Speciality_Title {
            get {
                return ResourceManager.GetString("Model_Speciality_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Type.
        /// </summary>
        public static string Model_Staff_Type {
            get {
                return ResourceManager.GetString("Model_Staff_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achivements.
        /// </summary>
        public static string Model_Student_Achivements {
            get {
                return ResourceManager.GetString("Model_Student_Achivements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Model_Student_Address1 {
            get {
                return ResourceManager.GetString("Model_Student_Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living address.
        /// </summary>
        public static string Model_Student_Address2 {
            get {
                return ResourceManager.GetString("Model_Student_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contracts.
        /// </summary>
        public static string Model_Student_Contracts {
            get {
                return ResourceManager.GetString("Model_Student_Contracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date entering.
        /// </summary>
        public static string Model_Student_DateEnter {
            get {
                return ResourceManager.GetString("Model_Student_DateEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date left.
        /// </summary>
        public static string Model_Student_DateLeft {
            get {
                return ResourceManager.GetString("Model_Student_DateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string Model_Student_Faculty {
            get {
                return ResourceManager.GetString("Model_Student_Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradebook number.
        /// </summary>
        public static string Model_Student_GradeBookNumber {
            get {
                return ResourceManager.GetString("Model_Student_GradeBookNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Model_Student_Group {
            get {
                return ResourceManager.GetString("Model_Student_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbies.
        /// </summary>
        public static string Model_Student_Hobbies {
            get {
                return ResourceManager.GetString("Model_Student_Hobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Foreign.
        /// </summary>
        public static string Model_Student_IsForeign {
            get {
                return ResourceManager.GetString("Model_Student_IsForeign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Model_Student_Languages {
            get {
                return ResourceManager.GetString("Model_Student_Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marks.
        /// </summary>
        public static string Model_Student_Marks {
            get {
                return ResourceManager.GetString("Model_Student_Marks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents.
        /// </summary>
        public static string Model_Student_Parents {
            get {
                return ResourceManager.GetString("Model_Student_Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality.
        /// </summary>
        public static string Model_Student_Speciality {
            get {
                return ResourceManager.GetString("Model_Student_Speciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Model_Student_Status {
            get {
                return ResourceManager.GetString("Model_Student_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Mode.
        /// </summary>
        public static string Model_Student_StudyMode {
            get {
                return ResourceManager.GetString("Model_Student_StudyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studetns.
        /// </summary>
        public static string Model_Student_Title {
            get {
                return ResourceManager.GetString("Model_Student_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Model_User_Email {
            get {
                return ResourceManager.GetString("Model_User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string Model_User_IsActive {
            get {
                return ResourceManager.GetString("Model_User_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User language.
        /// </summary>
        public static string Model_User_Language {
            get {
                return ResourceManager.GetString("Model_User_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Model_User_Password {
            get {
                return ResourceManager.GetString("Model_User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Model_User_Title {
            get {
                return ResourceManager.GetString("Model_User_Title", resourceCulture);
            }
        }
    }
}
