//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARM.Resource.AppResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARM.Resource.AppResource.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Enum_Female {
            get {
                return ResourceManager.GetString("Enum_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture.
        /// </summary>
        public static string Enum_Lecture {
            get {
                return ResourceManager.GetString("Enum_Lecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Enum_Male {
            get {
                return ResourceManager.GetString("Enum_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Enum_None {
            get {
                return ResourceManager.GetString("Enum_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phd.
        /// </summary>
        public static string Enum_Phd {
            get {
                return ResourceManager.GetString("Enum_Phd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technician.
        /// </summary>
        public static string Enum_Technician {
            get {
                return ResourceManager.GetString("Enum_Technician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Grid_Staff_Title {
            get {
                return ResourceManager.GetString("Grid_Staff_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universities.
        /// </summary>
        public static string Grid_University_Title {
            get {
                return ResourceManager.GetString("Grid_University_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM - bla - bla.
        /// </summary>
        public static string MAINWINDOW_TITLE {
            get {
                return ResourceManager.GetString("MAINWINDOW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string MENU_DOCUMENTS_TITLE {
            get {
                return ResourceManager.GetString("MENU_DOCUMENTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MENU_FILE_TITLE {
            get {
                return ResourceManager.GetString("MENU_FILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string MENU_HELP_TITLE {
            get {
                return ResourceManager.GetString("MENU_HELP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string MENU_REFERENCES_TITLE {
            get {
                return ResourceManager.GetString("MENU_REFERENCES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string MENU_REPORTS_TITLE {
            get {
                return ResourceManager.GetString("MENU_REPORTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string MENU_SERVICES_TITLE {
            get {
                return ResourceManager.GetString("MENU_SERVICES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universities.
        /// </summary>
        public static string Menu_University {
            get {
                return ResourceManager.GetString("Menu_University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Message_ErrorCaprion {
            get {
                return ResourceManager.GetString("Message_ErrorCaprion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Message_InformationCaption {
            get {
                return ResourceManager.GetString("Message_InformationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Message_QuestionCaption {
            get {
                return ResourceManager.GetString("Message_QuestionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        public static string Message_Save {
            get {
                return ResourceManager.GetString("Message_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Message_WarningCaption {
            get {
                return ResourceManager.GetString("Message_WarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Model_Action_Add {
            get {
                return ResourceManager.GetString("Model_Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Model_Action_Edit {
            get {
                return ResourceManager.GetString("Model_Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Model_Action_View {
            get {
                return ResourceManager.GetString("Model_Action_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Staff.
        /// </summary>
        public static string Model_Data_Staff {
            get {
                return ResourceManager.GetString("Model_Data_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} University.
        /// </summary>
        public static string Model_Data_University {
            get {
                return ResourceManager.GetString("Model_Data_University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        public static string Model_DateModified {
            get {
                return ResourceManager.GetString("Model_DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Model_Name {
            get {
                return ResourceManager.GetString("Model_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Model_Person_Email {
            get {
                return ResourceManager.GetString("Model_Person_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string Model_Person_FirstName {
            get {
                return ResourceManager.GetString("Model_Person_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Model_Person_LastName {
            get {
                return ResourceManager.GetString("Model_Person_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string Model_Person_MiddleName {
            get {
                return ResourceManager.GetString("Model_Person_MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home phone.
        /// </summary>
        public static string Model_Person_PhoneHome {
            get {
                return ResourceManager.GetString("Model_Person_PhoneHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone.
        /// </summary>
        public static string Model_Person_PhoneMobile {
            get {
                return ResourceManager.GetString("Model_Person_PhoneMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        public static string Model_Person_Sex {
            get {
                return ResourceManager.GetString("Model_Person_Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rector.
        /// </summary>
        public static string Model_Rector {
            get {
                return ResourceManager.GetString("Model_Rector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Type.
        /// </summary>
        public static string Model_Staff_Type {
            get {
                return ResourceManager.GetString("Model_Staff_Type", resourceCulture);
            }
        }
    }
}
