///////////////////////////////////////////////////////////
//  InvoiceBll.cs
//  Implementation of the Class InvoiceBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:42 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Invoice;
namespace ARM.Data.Implementation.Invoice {
    public class InvoiceBll : BaseBll<Models.Invoice>, IInvoiceBll
    {

		

	}//end InvoiceBll

}//end namespace Invoice