///////////////////////////////////////////////////////////
//  InvoiceDal.cs
//  Implementation of the Class InvoiceDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:42 PM
///////////////////////////////////////////////////////////

using ARM.Data.Interfaces.Invoice;
using ARM.Data.Layer.Context;
using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Implementation.Invoice
{
    /// <summary>
    /// Реалізація доступу до даних для рахунків
    /// </summary>
    public class InvoiceDal : BaseDal<Models.Invoice>, IInvoiceDal
    {
        /// <summary>
        /// Створити екземпляр <see cref="InvoiceDal"/> class.
        /// </summary>
        /// <param name="context">The context.</param>
        public InvoiceDal(IContext<Models.Invoice> context)
            : base(context)
        {
        }
    } //end InvoiceDal
} //end namespace Invoice