///////////////////////////////////////////////////////////
//  Achivement.cs
//  Implementation of the Class Achivement
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:37 PM
///////////////////////////////////////////////////////////

using System;

namespace ARM.Data.Models
{
    public class Achivement : BaseNoteModel
    {
        public Achivement()
        {
        }

        ~Achivement()
        {
        }

        public AchivementType Type
        {
            get;
            set;
        }

        public Guid StudentId
        {
            get;
            set;
        }

        public virtual Student Student
        {
            get;
            set;
        }
    }//end Achivement
}//end namespace Models