///////////////////////////////////////////////////////////
//  Address.cs
//  Implementation of the Class Address
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:37 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using ARM.Core.Attributes;
using ARM.Core.Enums;

namespace ARM.Data.Models
{
  [ARMMetadata(Metadata = eARMMetadata.Address)]
    public class Address : BaseModel
    {

        public Guid CountryId
        {
            get;
            set;
        }

        public string Region
        {
            get;
            set;
        }

        public string City
        {
            get;
            set;
        }

        public string Street
        {
            get;
            set;
        }

        public string House
        {
            get;
            set;
        }

        public string Apartment
        {
            get;
            set;
        }

        public virtual Country Country
        {
            get;
            set;
        }

    }//end Address
}//end namespace Models