///////////////////////////////////////////////////////////
//  AddressType.cs
//  Implementation of the Class AddressType
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:38 PM
///////////////////////////////////////////////////////////

namespace ARM.Data.Models
{
    /// <summary>
    /// Тип адрес
    /// </summary>
    public enum AddressType
    {
        None,
        Registration,
        Residence
    } //end AddressType
} //end namespace Models