///////////////////////////////////////////////////////////
//  BaseNoteModel.cs
//  Implementation of the Class BaseNoteModel
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:38 PM
///////////////////////////////////////////////////////////




using ARM.Data.Models;
namespace ARM.Data.Models {
	public class BaseNoteModel : BaseNamedModel {

		public BaseNoteModel(){

		}

		~BaseNoteModel(){

		}

		public string Note{
			get;
			set;
		}

	}//end BaseNoteModel

}//end namespace Models