///////////////////////////////////////////////////////////
//  BaseNamedModel.cs
//  Implementation of the Class BaseNamedModel
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:38 PM
///////////////////////////////////////////////////////////




using ARM.Data.Models;
namespace ARM.Data.Models {
	public class BaseNamedModel : BaseModel {

		public BaseNamedModel(){

		}

		~BaseNamedModel(){

		}

		public string Name{
			get;
			set;
		}

	}//end BaseNamedModel

}//end namespace Models