///////////////////////////////////////////////////////////
//  Class.cs
//  Implementation of the Class Class
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:38 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;

namespace ARM.Data.Models
{
    public class Class : BaseNamedModel
    {
        public Class()
        {
        }

        ~Class()
        {
        }

        public Guid StaffId
        {
            get;
            set;
        }

        public virtual Staff Lecturer
        {
            get;
            set;
        }

        public Guid SessionId { get; set; }
        public virtual Session Session { get; set; }

    }//end Class
}//end namespace Models