///////////////////////////////////////////////////////////
//  Contract.cs
//  Implementation of the Class Contract
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:39 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using ARM.Core.Attributes;
using ARM.Core.Enums;

namespace ARM.Data.Models
{
    /// <summary>
    /// Модель контракту
    /// </summary>
    [ARMMetadata(Metadata = eARMMetadata.Contract)]
    public class Contract : BaseNoteModel
    {
        [ARMRequired]
        [ARMGrid(Order = 2)]
        [Display(ResourceType = typeof(Resource.AppResource.Resources), Name = "Model_Contract_Number")]
        public string Number { get; set; }

        [ARMRequired]
        public EducationLevel Level { get; set; }

        [ARMRequired]
        [ARMGrid(Order = 3)]
        [Display(ResourceType = typeof(Resource.AppResource.Resources), Name = "Model_Contract_Parent")]
        public Guid? ParentId { get; set; }

        [ARMRequired]
        public Guid UniversityId { get; set; }

        [ARMRequired]
        public Guid? StudentId { get; set; }

        [ARMRequired]
        public Guid? SpecialityId { get; set; }

        [ARMRequired]
        public decimal Price { get; set; }

        public virtual Parent Customer { get; set; }

        public virtual University University { get; set; }

        public virtual Student Student { get; set; }

        public virtual Specialty Speciality { get; set; }

        public virtual IList<Invoice> Invoices { get; set; }
    } //end Contract
} //end namespace Models