///////////////////////////////////////////////////////////
//  Faculty.cs
//  Implementation of the Class Faculty
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:39 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ARM.Data.Models
{
    public class Faculty : BaseNamedModel
    {
        public Faculty()
        {
        }

        ~Faculty()
        {
        }

        public Guid? StaffId
        {
            get;
            set;
        }

        public virtual Staff Head
        {
            get;
            set;
        }

        public Guid UniversityId
        {
            get;
            set;
        }

        public virtual University University
        {
            get;
            set;
        }
        
        public virtual IList<Group> Groups { get; set; }
    }//end Faculty
}//end namespace Models