///////////////////////////////////////////////////////////
//  Faculty.cs
//  Implementation of the Class Faculty
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:39 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using ARM.Core.Attributes;
using ARM.Core.Enums;

namespace ARM.Data.Models
{
    /// <summary>
    /// Модель факультету
    /// </summary>
    [ARMMetadata(Metadata = eARMMetadata.Faculty)]
    public class Faculty : BaseNamedModel
    {
        /// <summary>
        /// Ініціалізіція нового екземпляра  <see cref="Faculty"/>.
        /// </summary>
        public Faculty()
        {
            
        }
        /// <summary>
        /// Отримує або задає ідентифікатор керівника.
        /// </summary>
        [ARMRequired]
        public Guid? StaffId
        {
            get;
            set;
        }

        /// <summary>
        /// Отримує або задає лінк.
        /// </summary>
        public string Url { get; set; }

        /// <summary>
        /// Отримує або задає завідуючого факультету.
        /// </summary>
        public virtual Staff Head
        {
            get;
            set;
        }

        /// <summary>
        /// Отримує або задає ідентифікатор університету.
        /// </summary>
        [ARMRequired]
        public Guid UniversityId
        {
            get;
            set;
        }

        /// <summary>
        /// Отримує або задає університет.
        /// </summary>
        public virtual University University
        {
            get;
            set;
        }

        /// <summary>
        /// Отримує або задає список груп.
        /// </summary>
        public virtual IList<Group> Groups { get; set; }

        /// <summary>
        /// Зручне представлення моделі для користувача. Повертає певне значення у вигляді рядка для відображеня в інтерфейсі.
        /// </summary>
        public override string Display
        {
            get { return Name; }
        }
    }//end Faculty
}//end namespace Models