///////////////////////////////////////////////////////////
//  Group.cs
//  Implementation of the Class Group
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:40 PM
///////////////////////////////////////////////////////////

using System.Collections.Generic;

namespace ARM.Data.Models
{
    public class Group : BaseNamedModel
    {
        public Group()
        {
        }

        ~Group()
        {
        }

        public long FacultyId
        {
            get;
            set;
        }

        public virtual Faculty Faculty
        {
            get;
            set;
        }

        public long StaffId
        {
            get;
            set;
        }

        public virtual Staff Curator
        {
            get;
            set;
        }

        public virtual IList<Student> Students
        {
            get;
            set;
        }
    }//end Group
}//end namespace Models