///////////////////////////////////////////////////////////
//  Hobby.cs
//  Implementation of the Class Hobby
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:40 PM
///////////////////////////////////////////////////////////

using System;
using ARM.Core.Attributes;
using ARM.Core.Enums;

namespace ARM.Data.Models
{
    /// <summary>
    /// Модель хобі
    /// </summary>
    [ARMMetadata(Metadata = eARMMetadata.Hobby)]
    public class Hobby : BaseNoteModel
    {
        /// <summary>
        /// Ініціалізіція нового екземпляра  <see cref="Hobby"/>.
        /// </summary>
        public Hobby()
        {
            
        }
        /// <summary>
        /// Отримує або задає ідентифікатор студента.
        /// </summary>
        public Guid StudentId
        {
            get;
            set;
        }

        /// <summary>
        /// Отримує або задає студента.
        /// </summary>
        public virtual Student Student
        {
            get;
            set;
        }
    }//end Hobby
}//end namespace Models