///////////////////////////////////////////////////////////
//  Invoice.cs
//  Implementation of the Class Invoice
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:42 PM
///////////////////////////////////////////////////////////


using System;
using ARM.Data.Models;
namespace ARM.Data.Models {
	public class Invoice : BaseNamedModel {

		public Invoice(){

		}

		~Invoice(){

		}

		public long ParentId{
			get;
			set;
		}

		public long ContractId{
			get;
			set;
		}

		public long SessionId{
			get;
			set;
		}

		public decimal Price{
			get;
			set;
		}

		public DateTime DateDue{
			get;
			set;
		}

		public InvoiceStatus Status{
			get;
			set;
		}

		public virtual Parent Customer{
			get;
			set;
		}

		public virtual Contract Contract{
			get;
			set;
		}

		public virtual Session Session{
			get;
			set;
		}

	}//end Invoice

}//end namespace Models