///////////////////////////////////////////////////////////
//  Mark.cs
//  Implementation of the Class Mark
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:43 PM
///////////////////////////////////////////////////////////

using System;
using System.ComponentModel.DataAnnotations;
using ARM.Core.Attributes;
using ARM.Core.Enums;

namespace ARM.Data.Models
{
    /// <summary>
    /// Модель оцінки
    /// </summary>
    [ARMMetadata(Metadata = eARMMetadata.Mark)]
    public class Mark : BaseNamedModel
    {
        /// <summary>
        /// Ініціалізіція нового екземпляра  <see cref="Mark"/>.
        /// </summary>
        public Mark()
        {
            
        }
        /// <summary>
        /// Отримує або задає ідентифікатор студента.
        /// </summary>
        [ARMRequired]
        public Guid? StudentId
        {
            get;
            set;
        }

        /// <summary>
        /// Отримує або задає ідентифікатор заняття.
        /// </summary>
        [ARMRequired]
        public Guid? ClassId
        {
            get;
            set;
        }

        /// <summary>
        /// Отримує або задає студента.
        /// </summary>
        [ARMGrid(Order = 2)]
        [Display(ResourceType = typeof(Resource.AppResource.Resources), Name = "Model_Mark_Student")]
        public virtual Student Student
        {
            get;
            set;
        }

        /// <summary>
        /// Отримує або задає класу/заняття.
        /// </summary>
        [ARMGrid(Order = 3)]
        [Display(ResourceType = typeof(Resource.AppResource.Resources), Name = "Model_Mark_Class")]
        public virtual Class Class
        {
            get;
            set;
        }

        /// <summary>
        /// Отримує або задає дату.
        /// </summary>
        [ARMRequired]
        [ARMGrid(Order = 7)]
        [Display(ResourceType = typeof(Resource.AppResource.Resources), Name = "Model_Mark_Date")]
        public DateTime? Date
        {
            get;
            set;
        }

        /// <summary>
        /// Отримує або задає тип оцінки.
        /// </summary>
        [ARMGrid(Order = 4)]
        [Display(ResourceType = typeof(Resource.AppResource.Resources), Name = "Model_Mark_Type")]
        public MarkType Type
        {
            get;
            set;
        }

        /// <summary>
        /// Отримує або задає значення.
        /// </summary>
        [ARMGrid(Order = 5)]
        [Display(ResourceType = typeof(Resource.AppResource.Resources), Name = "Model_Mark_MarkRate")]
        [ARMRange(Min = 0,Max = 100)]
        public decimal MarkRate { get; set; }

        /// <summary>
        /// Отримує або задає чи являється запис про атестацію.
        /// </summary>
        [ARMGrid(Order = 6)]
        [Display(ResourceType = typeof(Resource.AppResource.Resources), Name = "Model_Mark_IsCertification")]
        public bool IsCertification { get; set; }
    }//end Mark
}//end namespace Models