///////////////////////////////////////////////////////////
//  Parent.cs
//  Implementation of the Class Parent
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:44 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;

namespace ARM.Data.Models
{
    public class Parent : Person
    {
        public Parent()
        {
        }

        ~Parent()
        {
        }

        public Guid? StudentId
        {
            get;
            set;
        }

        public virtual Student Child
        {
            get;
            set;
        }

        public virtual IList<Contract> Contracts { get; set; }
        
    }//end Parent
}//end namespace Models