///////////////////////////////////////////////////////////
//  Payment.cs
//  Implementation of the Class Payment
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:44 PM
///////////////////////////////////////////////////////////

using System;

namespace ARM.Data.Models
{
    public class Payment : BaseNamedModel
    {
        public long ContractId { get; set; }

        public long ParentId { get; set; }

        public long InvoiceId { get; set; }

        public long SessionId { get; set; }

        public DateTime Date { get; set; }

        public decimal Sum { get; set; }

        public virtual Contract Contract { get; set; }

        public virtual Parent Customer { get; set; }

        public virtual Invoice Invoice { get; set; }

        public virtual Session Session { get; set; }

        ~Payment()
        {
        }
    } //end Payment
} //end namespace Models