///////////////////////////////////////////////////////////
//  Session.cs
//  Implementation of the Class Session
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:44 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;

namespace ARM.Data.Models
{
    public class Session : BaseNamedModel
    {
        public Session()
        {
        }

        ~Session()
        {
        }

        public DateTime DateBegin
        {
            get;
            set;
        }

        public DateTime DateEnd
        {
            get;
            set;
        }

        public ICollection<Class> Classes
        {
            get;
            set;
        }
    }//end Session
}//end namespace Models