///////////////////////////////////////////////////////////
//  Session.cs
//  Implementation of the Class Session
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:44 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using ARM.Core.Attributes;
using ARM.Core.Enums;

namespace ARM.Data.Models
{
  [ARMMetadata(Metadata = eARMMetadata.Session)]

    public class Session : BaseNamedModel
    {
        public DateTime DateBegin
        {
            get;
            set;
        }

        public DateTime DateEnd
        {
            get;
            set;
        }

        public virtual IList<Class> Classes
        {
            get;
            set;
        }
    }//end Session
}//end namespace Models