///////////////////////////////////////////////////////////
//  Session.cs
//  Implementation of the Class Session
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:44 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using ARM.Core.Attributes;
using ARM.Core.Enums;
using ARM.Resource.AppResource;

namespace ARM.Data.Models
{
    /// <summary>
    /// Модель семетру
    /// </summary>
    [ARMMetadata(Metadata = eARMMetadata.Session)]
    public class Session : BaseNamedModel
    {
        /// <summary>
        /// Ініціалізіція нового екземпляра  <see cref="Session"/>.
        /// </summary>
        public Session()
        {
            
        }
        /// <summary>
        /// Отримує або задає дату початку.
        /// </summary>
        [ARMRequired]
        [ARMGrid(Order = 2)]
        [Display(ResourceType = typeof (Resources), Name = "Model_Session_DateBegin")]
        public DateTime DateBegin { get; set; }

        /// <summary>
        /// Отримує або задає дату закінчення.
        /// </summary>
        [ARMRequired]
        [ARMGrid(Order = 3)]
        [Display(ResourceType = typeof (Resources), Name = "Model_Session_DateEnd")]
        public DateTime DateEnd { get; set; }

        /// <summary>
        /// Отримує або задає список кдасів/занятть.
        /// </summary>
        public virtual IList<Class> Classes { get; set; }
    } //end Session
} //end namespace Models