///////////////////////////////////////////////////////////
//  Specialty.cs
//  Implementation of the Class Specialty
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:45 PM
///////////////////////////////////////////////////////////

namespace ARM.Data.Models
{
    public class Specialty : BaseNamedModel
    {
        public Specialty()
        {
        }

        ~Specialty()
        {
        }

        public long FacultyId
        {
            get;
            set;
        }

        public virtual Faculty Faculty
        {
            get;
            set;
        }
    }//end Specialty
}//end namespace Models