///////////////////////////////////////////////////////////
//  Specialty.cs
//  Implementation of the Class Specialty
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:45 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Generic;
using ARM.Core.Attributes;
using ARM.Core.Enums;

namespace ARM.Data.Models
{
  [ARMMetadata(Metadata = eARMMetadata.Specialty)]

    public class Specialty : BaseNamedModel
    {
        public Specialty()
        {
        }

        ~Specialty()
        {
        }

        public Guid? FacultyId
        {
            get;
            set;
        }

        public virtual Faculty Faculty
        {
            get;
            set;
        }
        
    }//end Specialty
}//end namespace Models