///////////////////////////////////////////////////////////
//  Staff.cs
//  Implementation of the Class Staff
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:45 PM
///////////////////////////////////////////////////////////

using System.Collections;
using System.Collections.Generic;

namespace ARM.Data.Models
{
    public class Staff : Person
    {
        public Staff()
        {
        }

        ~Staff()
        {
        }

        public StaffType StaffType
        {
            get;
            set;
        }

        public virtual IList<Class> Classes { get; set; }
    }//end Staff
}//end namespace Models