///////////////////////////////////////////////////////////
//  Staff.cs
//  Implementation of the Class Staff
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:45 PM
///////////////////////////////////////////////////////////

namespace ARM.Data.Models
{
    public class Staff : Person
    {
        public Staff()
        {
        }

        ~Staff()
        {
        }

        public StaffType StaffType
        {
            get;
            set;
        }
    }//end Staff
}//end namespace Models