///////////////////////////////////////////////////////////
//  StudyMode.cs
//  Implementation of the Class StudyMode
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:46 PM
///////////////////////////////////////////////////////////

namespace ARM.Data.Models
{
    /// <summary>
    /// Режим навчання
    /// </summary>
    public enum StudyMode
    {
        FullTime,
        Distance
    } //end StudyMode
} //end namespace Models