///////////////////////////////////////////////////////////
//  Student.cs
//  Implementation of the Class Student
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:46 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ARM.Core.Attributes;
using ARM.Core.Enums;

namespace ARM.Data.Models
{
  [ARMMetadata(Metadata = eARMMetadata.Student)]

    public class Student : Person
    {
        [ARMRequired]
        public Guid AddressId { get; set; }

        [ForeignKey("AddressId")]
        public virtual Address Address { get; set; }

        [ARMRequired]
        public Guid LivingAddressId { get; set; }

        [ForeignKey("LivingAddressId")]
        public virtual Address LivingAddress { get; set; }

        public virtual IList<Parent> Parents
        {
            get;
            set;
        }

        public Guid? GroupId
        {
            get;
            set;
        }

        public virtual Group Group
        {
            get;
            set;
        }

        public virtual IList<Hobby> Hobbies
        {
            get;
            set;
        }

        public virtual IList<Achivement> Achivements
        {
            get;
            set;
        }

        public DateTime DateFirstEnter
        {
            get;
            set;
        }

        public DateTime DateLeft
        {
            get;
            set;
        }

        public virtual IList<Language> Languages
        {
            get;
            set;
        }

        [ARMRequired]
        public Guid? FacultyId
        {
            get;
            set;
        }

        public virtual Faculty Faculty
        {
            get;
            set;
        }

        public StudyMode StudyMode
        {
            get;
            set;
        }

        public string GradeBookNumber
        {
            get;
            set;
        }

        public virtual IList<Contract> Contracts { get; set; } 

        public bool IsForeign
        {
            get;
            set;
        }

        [ARMRequired]
        public Guid? SpecialityId
        {
            get;
            set;
        }

        public virtual Specialty Speciality
        {
            get;
            set;
        }

        public StudentStatus Status
        {
            get;
            set;
        }

        public virtual IList<Mark> Marks { get; set; }

    }//end Student
}//end namespace Models