///////////////////////////////////////////////////////////
//  AchivementDal.cs
//  Implementation of the Class AchivementDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:37 PM
///////////////////////////////////////////////////////////

using ARM.Data.Interfaces.Achivement;
using ARM.Data.Layer.Context;
using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Implementation.Achivement
{
    /// <summary>
    /// Реалізація доступу до даних для досягнень
    /// </summary>
    public class AchivementDal : BaseDal<Models.Achivement>, IAchivementDal
    {
        /// <summary>
        /// Створити екземпляр <see cref="AchivementDal"/> class.
        /// </summary>
        /// <param name="context">The context.</param>
        public AchivementDal(IContext<Models.Achivement> context)
            : base(context)
        {
        }
    } //end AchivementDal
} //end namespace Achivement