///////////////////////////////////////////////////////////
//  AchivementDal.cs
//  Implementation of the Class AchivementDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:37 PM
///////////////////////////////////////////////////////////

using ARM.Data.Interfaces.Achivement;
using ARM.Data.Layer.Context;
using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Implementation.Achivement
{
    public class AchivementDal : BaseDal<Models.Achivement>, IAchivementDal
    {
        public AchivementDal(IContext<Models.Achivement> context)
            : base(context)
        {
        }
    }//end AchivementDal
}//end namespace Achivement