///////////////////////////////////////////////////////////
//  SettingsBll.cs
//  Implementation of the Class SettingsBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:45 PM
///////////////////////////////////////////////////////////

using ARM.Data.Interfaces.Settings;
using ARM.Data.Layer.Context;
using ARM.Data.Layer.Interfaces;
using ARM.Data.Models;

namespace ARM.Data.Implementation.Settings
{
    public class SettingsBll : BaseBll<Models.SettingParameters>, ISettingsBll
    {
        public SettingsBll(IDal<SettingParameters> dal)
            : base(dal)
        {
        }
    }//end SettingsBll
}//end namespace Settings