///////////////////////////////////////////////////////////
//  SettingsDal.cs
//  Implementation of the Class SettingsDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:45 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Settings;
namespace ARM.Data.Implementation.Settings {
    public class SettingsDal : BaseDal<Models.SettingParameters>, ISettingsDal
    {

		

	}//end SettingsDal

}//end namespace Settings