///////////////////////////////////////////////////////////
//  SettingsContext.cs
//  Implementation of the Class SettingsContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:45 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Settings;
namespace ARM.Data.Implementation.Settings {
    public class SettingsContext : BaseContext<Models.SettingParameters>, ISettingsContext
    {


	}//end SettingsContext

}//end namespace Settings