///////////////////////////////////////////////////////////
//  IARMMainWorkspaceViewModel.cs
//  Implementation of the Interface IARMMainWorkspaceViewModel
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2014 1:37:55 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Windows.Input;
using ARM.Core.Interfaces;

namespace ARM.Module.Interfaces
{
    /// <summary>
    /// Інтерфейс головної моделі представлення.
    /// Інтерфейс відповідає за взаємодію всіх підсистем.
    /// </summary>
    public interface IARMMainWorkspaceViewModel : IARMViewModel
    {
        /// <summary>
        /// Отримує всі моделі з фким працює користувая в даний момент.
        /// </summary>
        ObservableCollection<IARMWorkspaceViewModel> Items { get; }

        /// <summary>
        /// Отриує та задає поточну модель представлення я кою працює користувач.
        /// </summary>
        IARMWorkspaceViewModel CurrentWorkspace { get; set; }

        /// <summary>
        /// Отримує головний інтерфейс користувача.
        /// </summary>
        IARMView MenuView { get; }

        /// <summary>
        /// Отримує інтерфейс користувача для панелі управління.
        /// </summary>
        IARMView ToolboxView { get; }

        /// <summary>
        /// Отримує інтерфейс користувача для панелі статуса.
        /// </summary>
        IARMView StatusBarView { get; }

        /// <summary>
        /// Отримує модель представлення для головного меню.
        /// </summary>
        IARMMainMenuViewModel Menu { get; }

        /// <summary>
        /// Отримує модель представлення для панелі управління.
        /// </summary>
        IARMMainToolboxViewModel Toolbox { get; }

        /// <summary>
        /// Отримує модель представлення для панелі статуса.
        /// </summary>
        IARMMainStatusBarViewModel StatusBar { get; }

        /// <summary>
        /// Отримує або задає індекс поточної моделі представлення.
        /// </summary>
        int CurrentWorkspaceIndex { get; set; }

        /// <summary>
        /// Команда закриття.
        /// </summary>
        ICommand ClosingCommand { get; }

        /// <summary>
        /// Подія, яка відбувається при закритті моделі.
        /// </summary>
        event EventHandler Close;

        /// <summary>
        /// Метод відбувається безпосередньо перед закритям, для допоміжної логіки.
        /// Наприклад, можливо відмінити закриття програми.
        /// </summary>
        void OnClosing(CancelEventArgs arg);
    } //end IARMMainWorkspaceViewModel
} //end namespace Interfaces