///////////////////////////////////////////////////////////
//  IARMMenuCommand.cs
//  Implementation of the Interface IARMMenuCommand
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2014 1:37:55 AM
///////////////////////////////////////////////////////////

using System.Windows.Input;

namespace ARM.Module.Interfaces
{
    public interface IARMMenuCommand : ICommand
    {
    }//end IARMMenuCommand
}//end namespace Interfaces