///////////////////////////////////////////////////////////
//  IARMMainMenuViewModel.cs
//  Implementation of the Interface IARMMainMenuViewModel
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2014 1:37:55 AM
///////////////////////////////////////////////////////////

using System.Collections.ObjectModel;
using ARM.Core.Interfaces;

namespace ARM.Module.Interfaces
{
    public interface IARMMainMenuViewModel : IARMViewModel
    {
        ObservableCollection<IARMMenuCommand> Files { get; }

        ObservableCollection<IARMMenuCommand> Documents { get; }

        ObservableCollection<IARMMenuCommand> References { get; }

        ObservableCollection<IARMMenuCommand> Reports { get; }

        ObservableCollection<IARMMenuCommand> Services { get; }

        ObservableCollection<IARMMenuCommand> Helps { get; }
    }//end IARMMainMenuViewModel
}//end namespace Interfaces