///////////////////////////////////////////////////////////
//  IARMMainMenuViewModel.cs
//  Implementation of the Interface IARMMainMenuViewModel
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2014 1:37:55 AM
///////////////////////////////////////////////////////////

using System.Collections.ObjectModel;
using ARM.Core.Interfaces;

namespace ARM.Module.Interfaces
{
    public interface IARMMainMenuViewModel : IARMViewModel
    {
        ObservableCollection<IARMMenuCommand> Files();

        ObservableCollection<IARMMenuCommand> Documents();

        ObservableCollection<IARMMenuCommand> References();

        ObservableCollection<IARMMenuCommand> Reports();

        ObservableCollection<IARMMenuCommand> Services();

        ObservableCollection<IARMMenuCommand> Helps();
    }//end IARMMainMenuViewModel
}//end namespace Interfaces