///////////////////////////////////////////////////////////
//  SessionBll.cs
//  Implementation of the Class SessionBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:44 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Session;
namespace ARM.Data.Implementation.Session {
    public class SessionBll : BaseBll<Models.Session>, ISessionBll
    {

	

	}//end SessionBll

}//end namespace Session