///////////////////////////////////////////////////////////
//  SessionContext.cs
//  Implementation of the Class SessionContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:44 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Session;
namespace ARM.Data.Implementation.Session {
    public class SessionContext : BaseContext<Models.Session>, ISessionContext
    {


	}//end SessionContext

}//end namespace Session