///////////////////////////////////////////////////////////
//  IClassContext.cs
//  Implementation of the Interface IClassContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:41 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Class
{
    /// <summary>
    /// Інтерфейс контексту для роботи з класами
    /// </summary>
    public interface IClassContext : IContext<Models.Class>
    {
    } //end IClassContext
} //end namespace Class