///////////////////////////////////////////////////////////
//  ISpecialtyDal.cs
//  Implementation of the Interface ISpecialtyDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:43 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Specialty
{
    /// <summary>
    /// Інтерфейс доступу до даних спеціальностей
    /// </summary>
    public interface ISpecialtyDal : IDal<Models.Specialty>
    {
    } //end ISpecialtyDal
} //end namespace Specialty