///////////////////////////////////////////////////////////
//  AddressDal.cs
//  Implementation of the Class AddressDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:37 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Address;
namespace ARM.Data.Implementation.Address {
    public class AddressDal : BaseDal<Models.Address>, IAddressDal
    {


	}//end AddressDal

}//end namespace Address