///////////////////////////////////////////////////////////
//  HobbyDal.cs
//  Implementation of the Class HobbyDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:40 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Hobby;
namespace ARM.Data.Implementation.Hobby {
    public class HobbyDal : BaseDal<Models.Hobby>, IHobbyDal
    {


	}//end HobbyDal

}//end namespace Hobby