namespace ARM.Module.Enums
{
    public enum eARMMainMenuCommand
    {
        None,
        Exit,
        About,
        DocumentContract,
        DocumentInvoice,
        DocumentPayment,
        ReferenceUniversity,
        ReferenceStaff,
        ReferenceLanguage,
        ReferenceCountry,
        ReferenceSettings,
        ReferenceFaculty,
        ReferenceGroup,
        ReferenceSession,
        ReferenceClass,
        ReferenceAddress,
        ReferenceParent,
        ReferenceSpeciality,
        ReferenceUser,
        ReferenceStudent,
        ReferenceEmployer,
        ServiceEvaluation,
        ServiceCalculationStipend, 
        ReportContractGroup,
        ReportCertification,
        ReportSessionMarks,
        ReportDebt
    }
}