///////////////////////////////////////////////////////////
//  ARMToolboxDeleteCommand.cs
//  Implementation of the Class ARMToolboxDeleteCommand
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2014 12:36:35 AM
///////////////////////////////////////////////////////////

using System;
using ARM.Core.Enums;
using ARM.Core.MVVM.Commands.Base;

namespace ARM.Core.MVVM.Commands
{
  /// <summary>
  /// Команда видалення запису
  /// </summary>
    public class ARMToolboxDeleteCommand : ARMToolboxCommandBase
    {
      /// <summary>
      /// Ініціалізує новий екземпляр класу <see cref="ARMToolboxDeleteCommand"/>.
      /// </summary>
      /// <param name="action">Дія.</param>
      /// <param name="predicate">Предикат.</param>
        public ARMToolboxDeleteCommand(Action<ToolbarCommand> action, Func<ToolbarCommand, bool> predicate) 
            : base(action, predicate)
        {
            Type = ToolbarCommand.Delete;
            Title = "Delete";
        }

        /// <summary>
        /// Ініціалізує новий екземпляр класу <see cref="ARMToolboxDeleteCommand"/>.
        /// </summary>
        /// <param name="action">Дія.</param>
        public ARMToolboxDeleteCommand(Action<ToolbarCommand> action) 
            : this(action,null)
        {
        }

        /// <summary>
        /// Визначає порядок.
        /// </summary>
        /// <returns></returns>
        protected override int GetOrder()
        {
            return 2;
        }
    }//end ARMToolboxDeleteCommand
}//end namespace Commands