///////////////////////////////////////////////////////////
//  ARMToolboxEditCommand.cs
//  Implementation of the Class ARMToolboxEditCommand
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2014 12:36:35 AM
///////////////////////////////////////////////////////////

using ARM.Core.MVVM.Commands.Base;

namespace ARM.Core.MVVM.Commands
{
    public class ARMToolboxEditCommand : ARMToolboxCommandBase
    {
        public ARMToolboxEditCommand()
        {
        }

    
    }//end ARMToolboxEditCommand
}//end namespace Commands