///////////////////////////////////////////////////////////
//  CountryContext.cs
//  Implementation of the Class CountryContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:39 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Country;
namespace ARM.Data.Implementation.Country {
    public class CountryContext : BaseContext<Models.Country>, ICountryContext
    {

	

	}//end CountryContext

}//end namespace Country