///////////////////////////////////////////////////////////
//  CountryBll.cs
//  Implementation of the Class CountryBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:39 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Country;
namespace ARM.Data.Implementation.Country {
    public class CountryBll : BaseBll<Models.Country>, ICountryBll
    {


	}//end CountryBll

}//end namespace Country