///////////////////////////////////////////////////////////
//  ICountryBll.cs
//  Implementation of the Interface ICountryBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:41 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Country
{

    /// <summary>
    /// Простір імен інтерфейсів для моделей даних - країни
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal class NamespaceDoc
    {
    }
    /// <summary>
    /// Інтерфейс бізнес логіки країн
    /// </summary>
    public interface ICountryBll : IBll<Models.Country>
    {
    } //end ICountryBll
} //end namespace Country