///////////////////////////////////////////////////////////
//  ARMEmailValidationRule.cs
//  Implementation of the Class ARMEmailValidationRule
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:42 PM
///////////////////////////////////////////////////////////

using ARM.Core.Interfaces;

namespace ARM.Core.Validation.Rules
{
    public class ARMEmailValidationRule : ARMStringValidationRule
    {
        ~ARMEmailValidationRule()
        {
        }

        protected override IARMValidationResult InternalEvalute(object val)
        {
            return null;
        }
    } //end ARMEmailValidationRule
} //end namespace Rules