///////////////////////////////////////////////////////////
//  ARMEmailValidationRule.cs
//  Implementation of the Class ARMEmailValidationRule
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:42 PM
///////////////////////////////////////////////////////////

namespace ARM.Core.Validation.Rules
{
  /// <summary>
  /// Класс-правило для для валідації властивостей, що представляють собою Email
  /// </summary>
  public class ARMEmailValidationRule : ARMStringValidationRule
  {
    /// <summary>
    /// Ініціалізує новий екземпляр класу <see cref="ARMEmailValidationRule"/>.
    /// </summary>
    public ARMEmailValidationRule()
    {
    }

    /// <summary>
    /// Метод валідації
    /// </summary>
    /// <param name="val">Значення для валідації.</param>
    /// <returns>результат валідації</returns>
    protected override ARM.Core.Interfaces.IARMValidationResult InternalEvalute(object val)
    {
      return null;
    }
  }//end ARMEmailValidationRule
}//end namespace Rules