///////////////////////////////////////////////////////////
//  ARMMInValidationRule.cs
//  Implementation of the Class ARMMInValidationRule
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:42 PM
///////////////////////////////////////////////////////////

using System;

namespace ARM.Core.Validation.Rules
{
    /// <summary>
    /// Класс-правило для валідації мінімаальних числових начень
    /// </summary>
    public class ARMMinValidationRule : ARMNumericValidationRule
    {
        /// <summary>
        /// Ініціалізує новий екземпляр класу
        /// </summary>
        public ARMMinValidationRule()
        {
        }

        /// <summary>
        /// Валідації значення.
        /// </summary>
        /// <param name="val">Значення.</param>
        /// <returns></returns>
        protected override ARM.Core.Interfaces.IARMValidationResult InternalEvalute(object val)
        {
            var result = new ARMValidationResult() { IsValid = true };
            if (val != null)
            {
                double v = Convert.ToDouble(val);
                result.IsValid = Min < v;
                if (!result.IsValid)
                {
                    result.AddMessage(string.Format("Value shouldn't be less {0}.", Min));
                }
            }
            return result;
        }

        /// <summary>
        /// Ініціалізує новий екземпляр класу
        /// </summary>
        /// <param name="min">Мінімальна границя</param>
        /// <param name="max">Максимальна границя</param>
        public ARMMinValidationRule(double min, double max)
            : base(min, max)
        {
        }
    }//end ARMMInValidationRule
}//end namespace Rules