///////////////////////////////////////////////////////////
//  ARMMobilPhoneValidationRule.cs
//  Implementation of the Class ARMMobilPhoneValidationRule
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:43 PM
///////////////////////////////////////////////////////////

namespace ARM.Core.Validation.Rules
{
  /// <summary>
  /// Класс-правило для валідації властисовстей, що представляють значення мобільного
  /// </summary>
    public class ARMMobilPhoneValidationRule : ARMStringValidationRule
    {

      /// <summary>
      /// Валідація значення.
      /// </summary>
      /// <param name="val">Значення.</param>
      /// <returns></returns>
        protected override ARM.Core.Interfaces.IARMValidationResult InternalEvalute(object val)
        {
            return null;
        }
    }//end ARMMobilPhoneValidationRule
}//end namespace Rules