///////////////////////////////////////////////////////////
//  ARMRangeValidationRule.cs
//  Implementation of the Class ARMRangeValidationRule
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:43 PM
///////////////////////////////////////////////////////////

namespace ARM.Core.Validation.Rules
{
    public class ARMRangeValidationRule : ARMNumericValidationRule
    {
        public ARMRangeValidationRule()
        {
        }

        ~ARMRangeValidationRule()
        {
        }

        ///
        /// <param name="min"></param>
        /// <param name="max"></param>
        public ARMRangeValidationRule(decimal min, decimal max)
        {
        }

        protected override ARM.Core.Interfaces.IARMValidationResult InternalEvalute()
        {
            return null;
        }
    }//end ARMRangeValidationRule
}//end namespace Rules