///////////////////////////////////////////////////////////
//  ARMStringValidationRule.cs
//  Implementation of the Class ARMStringValidationRule
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:43 PM
///////////////////////////////////////////////////////////

namespace ARM.Core.Validation.Rules
{
    public class ARMStringValidationRule : ARMValidationRule
    {
        protected ARMStringValidationRule()
        {
        }

        protected string Pattern { get; set; }

        ~ARMStringValidationRule()
        {
        }
    } //end ARMStringValidationRule
} //end namespace Rules