///////////////////////////////////////////////////////////
//  ARMStringValidationRule.cs
//  Implementation of the Class ARMStringValidationRule
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:43 PM
///////////////////////////////////////////////////////////

namespace ARM.Core.Validation.Rules
{
  /// <summary>
  /// Базовий класс-правило для валідації строкових значень.
  /// </summary>
    public class ARMStringValidationRule : ARMValidationRule
    {

      /// <summary>
      /// Ініціалізує новий екземпляр класу <see cref="ARMStringValidationRule"/>.
      /// </summary>
        protected ARMStringValidationRule()
        {
        }

        /// <summary>
        /// Встановлення або повернення шаблону для валідації строкових значень.
        /// </summary>
        protected string Pattern
        {
            get;
            set;
        }
    }//end ARMStringValidationRule
}//end namespace Rules