///////////////////////////////////////////////////////////
//  ARMUrlValidationRule.cs
//  Implementation of the Class ARMUrlValidationRule
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:43 PM
///////////////////////////////////////////////////////////

namespace ARM.Core.Validation.Rules
{
  /// <summary>
  /// Класс-правило для валідції значень які предщставляюь собою URL
  /// </summary>
    public class ARMUrlValidationRule : ARMStringValidationRule
    {

      /// <summary>
      /// Валідація значення.
      /// </summary>
      /// <param name="val">Значення.</param>
      /// <returns></returns>
        protected override ARM.Core.Interfaces.IARMValidationResult InternalEvalute(object val)
        {
            return null;
        }
    }//end ARMUrlValidationRule
}//end namespace Rules