///////////////////////////////////////////////////////////
//  ARMUrlValidationRule.cs
//  Implementation of the Class ARMUrlValidationRule
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:43 PM
///////////////////////////////////////////////////////////

using ARM.Core.Interfaces;

namespace ARM.Core.Validation.Rules
{
    public class ARMUrlValidationRule : ARMStringValidationRule
    {
        ~ARMUrlValidationRule()
        {
        }

        protected override IARMValidationResult InternalEvalute(object val)
        {
            return null;
        }
    } //end ARMUrlValidationRule
} //end namespace Rules