///////////////////////////////////////////////////////////
//  CoreModule.cs
//  Implementation of the Class CoreModule
//  Generated by Enterprise Architect
//  Created on:      31-Mar-2014 11:49:54 PM
///////////////////////////////////////////////////////////


using Microsoft.Practices.Prism.Modularity;

namespace ARM.Core {
	public class CoreModule : IModule {

		public CoreModule(){

		}

	    public void Initialize()
	    {
	        throw new System.NotImplementedException();
	    }
	}//end CoreModule

}//end namespace ARM.Core