///////////////////////////////////////////////////////////
//  IARMFacade.cs
//  Implementation of the Interface IARMFacade
//  Generated by Enterprise Architect
//  Created on:      30-Mar-2014 8:12:16 PM
///////////////////////////////////////////////////////////

using ARM.Core.Interfaces;
using ARM.Data.Models;

namespace ARM.Infrastructure.Interfaces
{
    /// <summary>
    /// Інтерфейс для досупу до загальних підсистем.
    /// </summary>
    public interface IARMFacade
    {
        /// <summary>
        /// Отримує підсистему логування.
        /// </summary>
        IARMLoggerFacade Logger { get; }

        /// <summary>
        /// Отримує підсистему повідомлень.
        /// </summary>
        IARMMessageBoxFacade MessageBox { get; }

        /// <summary>
        /// Отримує  або задає поточного покистувача.
        /// </summary>
        User CurrentUser { get; set; }
    } //end IARMFacade
} //end namespace Interfaces