///////////////////////////////////////////////////////////
//  IARMMessageBoxFacade.cs
//  Implementation of the Interface IARMMessageBoxFacade
//  Generated by Enterprise Architect
//  Created on:      30-Mar-2014 8:12:16 PM
///////////////////////////////////////////////////////////

using System.Windows;

namespace ARM.Infrastructure.Interfaces
{
    /// <summary>
    /// Інтерчейс для доступу доя функціональності повідомлень.
    /// </summary>
    public interface IARMMessageBoxFacade
    {
        /// <summary>
        /// Показує вказане повідомлення.
        /// </summary>
        /// <param name="message">Повідомлення.</param>
        /// <returns></returns>
        MessageBoxResult Show(string message);

        /// <summary>
        /// Показує попередження.
        /// </summary>
        /// <param name="message">Повідомлення.</param>
        /// <returns></returns>
        MessageBoxResult ShowWarning(string message);

        /// <summary>
        /// Показує повідомлення з запитанням.
        /// </summary>
        /// <param name="message">Повідомлення.</param>
        /// <returns></returns>
        MessageBoxResult ShowQuestion(string message);

        /// <summary>
        /// Показує повідомлення про помилку.
        /// </summary>
        /// <param name="message">Повідомлення.</param>
        /// <returns></returns>
        MessageBoxResult ShowError(string message);
    } //end IARMMessageBoxFacade
} //end namespace Interfaces