///////////////////////////////////////////////////////////
//  GroupBll.cs
//  Implementation of the Class GroupBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:40 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Group;
namespace ARM.Data.Implementation.Group {
    public class GroupBll : BaseBll<Models.Group>, IGroupBll
    {

		

	}//end GroupBll

}//end namespace Group