///////////////////////////////////////////////////////////
//  GroupDal.cs
//  Implementation of the Class GroupDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:40 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Group;
namespace ARM.Data.Implementation.Group {
    public class GroupDal : BaseDal<Models.Group>, IGroupDal
    {


	}//end GroupDal

}//end namespace Group