///////////////////////////////////////////////////////////
//  GroupDal.cs
//  Implementation of the Class GroupDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:40 PM
///////////////////////////////////////////////////////////

using ARM.Data.Interfaces.Group;
using ARM.Data.Layer.Context;
using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Implementation.Group
{
    public class GroupDal : BaseDal<Models.Group>, IGroupDal
    {
        public GroupDal(IContext<Models.Group> context)
            : base(context)
        {
        }
    } //end GroupDal
} //end namespace Group