///////////////////////////////////////////////////////////
//  UniversityDal.cs
//  Implementation of the Class UniversityDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:46 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.University;
namespace ARM.Data.Implementation.University {
    public class UniversityDal : BaseDal<Models.University>, IUniversityDal
    {


	}//end UniversityDal

}//end namespace University