///////////////////////////////////////////////////////////
//  IARMModelPropertyInfo.cs
//  Implementation of the Interface IARMModelPropertyInfo
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////

using System;
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace ARM.Core.Interfaces
{
    public interface IARMModelPropertyInfo
    {
        PropertyInfo Property
        {
            get;
        }

        bool IsRequired
        {
            get;
        }

        Type ReturnType
        {
            get;
        }

        IARMValidationAttribute ValidationAttribute
        {
            get;
        }

        bool VisibleInGrid { get; }

        DisplayAttribute Display { get; }

    }//end IARMModelPropertyInfo
}//end namespace Interfaces