///////////////////////////////////////////////////////////
//  IARMModelPropertyInfo.cs
//  Implementation of the Interface IARMModelPropertyInfo
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////

using System;
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace ARM.Core.Interfaces
{
    /// <summary>
    /// Інтерфейс-контейнер інформації про тип PropertyInfo всіх властивостей певного типу
    /// </summary>
    public interface IARMModelPropertyInfo
    {
        /// <summary>
        /// Повертає властивість
        /// </summary>
        PropertyInfo Property
        {
            get;
        }

        /// <summary>
        /// Повертає знаяення, що показує, ща властивість є обовязковоє до заповнення.
        /// </summary>
        /// <value>
        /// <c>true</c> якщо обовязкова; інакше, <c>false</c>.
        /// </value>
        bool IsRequired
        {
            get;
        }

        /// <summary>
        /// Повертає тип результату
        /// </summary>
        Type ReturnType
        {
            get;
        }

        /// <summary>
        /// Повертає атрибут валідації
        /// </summary>
        IARMValidationAttribute ValidationAttribute
        {
            get;
        }

        /// <summary>
        /// Чи властивість повинна відображатись у сітці
        /// </summary>
        /// <value>
        ///   <c>true</c> якшо повинна відображатись; інакше, <c>false</c>.
        /// </value>
        bool VisibleInGrid { get; }

        /// <summary>
        /// Повертає індекс відображення в сітці
        /// </summary>
        /// <value>
        /// The order in grid.
        /// </value>
        int OrderInGrid { get; }

        /// <summary>
        /// Атрибут для локалізації. За допомогою цього атрибуту можна вибрати локалізовані дані
        /// </summary>
        DisplayAttribute Display { get; }
    }//end IARMModelPropertyInfo
}//end namespace Interfaces