///////////////////////////////////////////////////////////
//  IARMDataViewModel.cs
//  Implementation of the Interface IARMDataViewModel
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////




using ARM.Core.Interfaces;
namespace ARM.Core.Interfaces {
	public interface IARMDataViewModel : IARMViewModel  {

		/// 
		/// <param name="obj"></param>
		void SetBusinessObject(object obj);

		object GetBusinessObject();
	}//end IARMDataViewModel

}//end namespace Interfaces