///////////////////////////////////////////////////////////
//  IARMValidationAttribute.cs
//  Implementation of the Interface IARMValidationAttribute
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////

namespace ARM.Core.Interfaces
{
    public interface IARMValidationAttribute
    {
    }//end IARMValidationAttribute
}//end namespace Interfaces