///////////////////////////////////////////////////////////
//  IARMViewModel.cs
//  Implementation of the Interface IARMViewModel
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////

using System.ComponentModel;

namespace ARM.Core.Interfaces
{
    public interface IARMViewModel : INotifyPropertyChanged
    {
        IARMView View
        {
            get;
        }
    }//end IARMViewModel
}//end namespace Interfaces