///////////////////////////////////////////////////////////
//  IARMValidationAdaptor.cs
//  Implementation of the Interface IARMValidationAdaptor
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq.Expressions;
using ARM.Core.EventArguments;

namespace ARM.Core.Interfaces
{
    /// <summary>
    ///     Інтерфейс, який забеспечує базову функціональність валідації
    /// </summary>
    public interface IARMValidationAdaptor : IDataErrorInfo
    {
        /// <summary>
        ///     Установка обєкта валідації
        /// </summary>
        /// <param name="obj">Обєкт.</param>
        /// <param name="listPi">Список властивостей.</param>
        void SetValidationObject(object obj, IList<IARMModelPropertyInfo> listPi);

        /// <summary>
        ///     Додати правило валідації.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="expression">Вираз.</param>
        /// <param name="rule">Правивило.</param>
        void AddRule<T>(Expression<Func<T>> expression, IARMValidationRule rule);

        /// <summary>
        /// Видаляє правило для валідації певної властивості.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="expression">Вираз.</param>
        void DeleteRule<T>(Expression<Func<T>> expression);

        /// <summary>
        ///     Зовнішній виклик валідації.
        /// </summary>
        /// <param name="name">Назва властивості.</param>
        void Validate(string name);

        /// <summary>
        ///     Зовнішній виклик валідації.
        /// </summary>
        /// <param name="propName">Вираз з властивістю.</param>
        void Validate<T>(Expression<Func<T>> propName);

        /// <summary>
        ///     Запуск валідації всіх властивостей.
        /// </summary>
        void ValidateAll();

        /// <summary>
        ///     Подія, яка виконується після закінчення валідації.
        ///     Повертає результат валідації.
        /// </summary>
        event EventHandler<ValidationEventArgs> ValidationCompleted;

        /// <summary>
        ///     Повернути результат
        /// </summary>
        /// <param name="propName">Вираз з властивістю.</param>
        /// <returns></returns>
        string GetResult<T>(Expression<Func<T>> propName);

        /// <summary>
        ///     Повернути результат валідації.
        /// </summary>
        /// <param name="name">Назва властивості.</param>
        /// <returns></returns>
        string GetResult(string name);

        /// <summary>
        ///     Повернути всі результати.
        /// </summary>
        /// <returns></returns>
        Dictionary<string, string> GetResultForAll();
    } //end IARMValidationAdaptor
} //end namespace Interfaces