///////////////////////////////////////////////////////////
//  IARMViewModel.cs
//  Implementation of the Interface IARMViewModel
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////

using System;
using System.ComponentModel;

namespace ARM.Core.Interfaces
{
  /// <summary>
  /// Базовий інтерфейс для моделей представлення аплікації
  /// </summary>
    public interface IARMViewModel : INotifyPropertyChanged,IDisposable
    {
      /// <summary>
      /// Користувацбкий інтерфейс закріплений за дано. моделюю прпедставлення.
      /// </summary>
        IARMView View
        {
            get;
        }
    }//end IARMViewModel
}//end namespace Interfaces