///////////////////////////////////////////////////////////
//  IARMModelPropertyInfo.cs
//  Implementation of the Interface IARMModelPropertyInfo
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////


using System;
using System.Reflection;

namespace ARM.Core.Interfaces {
	public interface IARMModelPropertyInfo  {

		PropertyInfo Property{
			get;
			set;
		}

		bool IsRequired{
			get;
			set;
		}

		Type ReturnType{
			get;
			set;
		}

		IARMValidationAttribute ValidationAttribute{
			get;
			set;
		}
	}//end IARMModelPropertyInfo

}//end namespace Interfaces