///////////////////////////////////////////////////////////
//  IARMValidationAdaptor.cs
//  Implementation of the Interface IARMValidationAdaptor
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////


using System;
using System.ComponentModel;
using System.Linq.Expressions;
using ARM.Core.EventArguments;

namespace ARM.Core.Interfaces {
	public interface IARMValidationAdaptor : IDataErrorInfo  {

		void InitializeRules();

		/// 
		/// <param name="rule"></param>
		void AddRule(IARMValidationRule rule);

		/// 
		/// <param name="propName"></param>
		void Validate<T>(Expression<Func<T>> propName);

		void ValidateAll();

		event EventHandler<ValidationEventArgs> ValidationCompleted;

		/// 
		/// <param name="propName"></param>
		string GetResult<T>(Expression<Func<T>> propName);

		string GetResultForAll();
	}//end IARMValidationAdaptor

}//end namespace Interfaces