///////////////////////////////////////////////////////////
//  IARMGridViewModel.cs
//  Implementation of the Interface IARMGridViewModel
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using ARM.Core.Enums;
using ARM.Core.Interfaces.Data;
using ARM.Core.Module;

namespace ARM.Core.Interfaces
{
  /// <summary>
  /// Інтерфейс для моделі, яка представляє дані у вигляді сітки
  /// </summary>
  /// <typeparam name="T">Тип даних,  які відображаються</typeparam>
    public interface IARMGridViewModel<T> : IARMWorkspaceViewModel where T : IARMModel
    {
      /// <summary>
      /// Колекція даних
      /// </summary>
        IEnumerable<T> DataSource
        {
            get;
        }


        /// <summary>
        /// Метод, який оброблює натискання кнопок на панелі управління
        /// </summary>
        /// <param name="cmdType">Тип команди.</param>
        void DoCommand(ToolbarCommand cmdType);

        /// <summary>
        /// Модель панелі управліня
        /// </summary>
        IARMToolboxViewModel Toolbox
        {
            get;
        }

        /// <summary>
        /// Повертає тип моделі даних
        /// </summary>
        /// <value>
        /// The type of the entity.
        /// </value>
        Type EntityType { get; }

        /// <summary>
        /// Встановлює або повертає вибрану модель в сітці
        /// </summary>
        T SelectedEntity { get; set; }

    }//end IARMGridViewModel
}//end namespace Interfaces