///////////////////////////////////////////////////////////
//  IARMValidationRule.cs
//  Implementation of the Interface IARMValidationRule
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////

namespace ARM.Core.Interfaces
{
    /// <summary>
    ///     Інтерфес правила валідації
    /// </summary>
    public interface IARMValidationRule
    {
        /// <summary>
        ///     Запустити валідацію.
        /// </summary>
        /// <param name="val">Обєкт валідації.</param>
        /// <returns></returns>
        IARMValidationResult Evalute(object val);
    } //end IARMValidationRule
} //end namespace Interfaces