///////////////////////////////////////////////////////////
//  IARMToolboxViewModel.cs
//  Implementation of the Interface IARMToolboxViewModel
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 4:59:44 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using ARM.Core.Enums;

namespace ARM.Core.Interfaces
{
    /// <summary>
    ///     Інтерфейс моделі представлення панелі управління.
    /// </summary>
    public interface IARMToolboxViewModel : IARMViewModel
    {
        /// <summary>
        ///     Список команд панелі управління.
        /// </summary>
        IEnumerable<IARMToolboxCommand> Commands { get; }

        /// <summary>
        ///     Ініціалізація панелі управління.
        /// </summary>
        void InitializeCommands();

        /// <summary>
        ///     Додати команду.
        /// </summary>
        /// <param name="cmd">Команда.</param>
        void AddCommand(IARMToolboxCommand cmd);

        /// <summary>
        ///     Втановити зовнішні обробчики натискань.
        /// </summary>
        /// <param name="action">Метод.</param>
        /// <param name="predicate">Предикат.</param>
        void SetActions(Action<ToolbarCommand> action, Func<ToolbarCommand, bool> predicate);
    } //end IARMToolboxViewModel
} //end namespace Interfaces