///////////////////////////////////////////////////////////
//  IAchivementContext.cs
//  Implementation of the Interface IAchivementContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:40 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Achivement
{
    /// <summary>
    /// Інтерфейс контекстуу для роботи з досягненнями
    /// </summary>
    public interface IAchivementContext : IContext<Models.Achivement>
    {
    } //end IAchivementContext
} //end namespace Achivement