///////////////////////////////////////////////////////////
//  IAchivementDal.cs
//  Implementation of the Interface IAchivementDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:40 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Achivement
{
    /// <summary>
    /// Інтерфейс доступу до даних досягнень
    /// </summary>
    public interface IAchivementDal : IDal<Models.Achivement>
    {
    } //end IAchivementDal
} //end namespace Achivement