///////////////////////////////////////////////////////////
//  IGroupBll.cs
//  Implementation of the Interface IGroupBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:41 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Interfaces;
namespace ARM.Data.Interfaces.Group {
    public interface IGroupBll : IBll<Models.Group>
    {

	}//end IGroupBll

}//end namespace Group