///////////////////////////////////////////////////////////
//  IContractDal.cs
//  Implementation of the Interface IContractDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:41 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Contract
{
    public interface IContractDal : IDal<Models.Contract>
    {
    } //end IContractDal
} //end namespace Contract