///////////////////////////////////////////////////////////
//  IAddressContext.cs
//  Implementation of the Interface IAddressContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:40 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Address
{
    /// <summary>
    /// Інтерфейс контексту для роботи з адресами
    /// </summary>
    public interface IAddressContext : IContext<Models.Address>
    {
    } //end IAddressContext
} //end namespace Address