///////////////////////////////////////////////////////////
//  IAddressDal.cs
//  Implementation of the Interface IAddressDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:40 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Interfaces;
namespace ARM.Data.Interfaces.Address {
    public interface IAddressDal : IDal<Models.Address>
    {

	}//end IAddressDal

}//end namespace Address