///////////////////////////////////////////////////////////
//  IAddressBll.cs
//  Implementation of the Interface IAddressBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:40 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Address
{

    /// <summary>
    /// Простір імен інтерфейсів для моделей даних - адреси.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal class NamespaceDoc
    {
    }
    /// <summary>
    /// Інтерфейс бізнес логіки адрес
    /// </summary>
    public interface IAddressBll : IBll<Models.Address>
    {
    } //end IAddressBll
} //end namespace Address