///////////////////////////////////////////////////////////
//  LogLevel.cs
//  Implementation of the Class LogLevel
//  Generated by Enterprise Architect
//  Created on:      30-Mar-2014 8:12:16 PM
///////////////////////////////////////////////////////////

namespace ARM.Infrastructure.Enums
{
    public enum LogLevel : int
    {
        None,
        Warning,
        Info,
        Error
    }//end LogLevel
}//end namespace Enums