///////////////////////////////////////////////////////////
//  ISessionBll.cs
//  Implementation of the Interface ISessionBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:42 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Session
{
    public interface ISessionBll : IBll<Models.Session>
    {
    }//end ISessionBll
}//end namespace Session