///////////////////////////////////////////////////////////
//  ISessionDal.cs
//  Implementation of the Interface ISessionDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:42 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Session
{
    public interface ISessionDal : IDal<Models.Session>
    {
    } //end ISessionDal
} //end namespace Session