///////////////////////////////////////////////////////////
//  IParentContext.cs
//  Implementation of the Interface IParentContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:42 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Parent
{
    /// <summary>
    /// Інтерфейс контексту для роботи з батьками
    /// </summary>
    public interface IParentContext : IContext<Models.Parent>
    {
    } //end IParentContext
} //end namespace Parent