///////////////////////////////////////////////////////////
//  FacultyBll.cs
//  Implementation of the Class FacultyBll
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:39 PM
///////////////////////////////////////////////////////////

using ARM.Data.Interfaces.Faculty;
using ARM.Data.Layer.Context;
using ARM.Data.Layer.Interfaces;


namespace ARM.Data.Implementation.Faculty
{
/// <summary>
/// Простір імен для реалізації функциональності по роботі з - факультетами
/// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    internal class NamespaceDoc
    {
    }

    /// <summary>
    /// Реалізація бізнес логіки для факультетів
    /// </summary>
    public class FacultyBll : BaseBll<Models.Faculty>, IFacultyBll
    {
        /// <summary>
        /// Створити екземпляр <see cref="FacultyBll"/> class.
        /// </summary>
        /// <param name="dal">The dal.</param>
        public FacultyBll(IDal<Models.Faculty> dal)
            : base(dal)
        {
        }
    } //end FacultyBll
} //end namespace Faculty