///////////////////////////////////////////////////////////
//  FacultyDal.cs
//  Implementation of the Class FacultyDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:40 PM
///////////////////////////////////////////////////////////

using ARM.Data.Interfaces.Faculty;
using ARM.Data.Layer.Context;
using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Implementation.Faculty
{
    /// <summary>
    /// Реалізація доступу до даних для факультетів
    /// </summary>
    public class FacultyDal : BaseDal<Models.Faculty>, IFacultyDal
    {
        public FacultyDal(IContext<Models.Faculty> context)
            : base(context)
        {
        }
    } //end FacultyDal
} //end namespace Faculty