///////////////////////////////////////////////////////////
//  FacultyContext.cs
//  Implementation of the Class FacultyContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:39 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Faculty;
namespace ARM.Data.Implementation.Faculty {
    public class FacultyContext : BaseContext<Models.Faculty>, IFacultyContext
    {


	}//end FacultyContext

}//end namespace Faculty