///////////////////////////////////////////////////////////
//  FacultyDal.cs
//  Implementation of the Class FacultyDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:40 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Context;
using ARM.Data.Interfaces.Faculty;
namespace ARM.Data.Implementation.Faculty {
    public class FacultyDal : BaseDal<Models.Faculty>, IFacultyDal
    {
	}//end FacultyDal

}//end namespace Faculty