namespace ARM.Data.CommonContextMigrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddUser : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Parent", "AddressId", "dbo.Address");
            DropForeignKey("dbo.Student", "AddressId", "dbo.Address");
            DropForeignKey("dbo.Student", "LivingAddressId", "dbo.Address");
            DropForeignKey("dbo.Address", "CountryId", "dbo.Country");
            DropForeignKey("dbo.Invoice", "ContractId", "dbo.Contract");
            DropForeignKey("dbo.Payment", "InvoiceId", "dbo.Invoice");
            DropForeignKey("dbo.Class", "SessionId", "dbo.Session");
            DropForeignKey("dbo.Invoice", "SessionId", "dbo.Session");
            DropForeignKey("dbo.Mark", "ClassId", "dbo.Class");
            DropForeignKey("dbo.Contract", "SpecialityId", "dbo.Specialty");
            DropForeignKey("dbo.Student", "SpecialityId", "dbo.Specialty");
            DropForeignKey("dbo.Group", "FacultyId", "dbo.Faculty");
            DropForeignKey("dbo.Specialty", "FacultyId", "dbo.Faculty");
            DropForeignKey("dbo.Student", "FacultyId", "dbo.Faculty");
            DropForeignKey("dbo.Student", "GroupId", "dbo.Group");
            DropForeignKey("dbo.Faculty", "UniversityId", "dbo.University");
            DropForeignKey("dbo.Contract", "UniversityId", "dbo.University");
            DropPrimaryKey("dbo.Achivement");
            DropPrimaryKey("dbo.Address");
            DropPrimaryKey("dbo.Country");
            DropPrimaryKey("dbo.Contract");
            DropPrimaryKey("dbo.Invoice");
            DropPrimaryKey("dbo.Payment");
            DropPrimaryKey("dbo.Session");
            DropPrimaryKey("dbo.Class");
            DropPrimaryKey("dbo.Specialty");
            DropPrimaryKey("dbo.Faculty");
            DropPrimaryKey("dbo.Group");
            DropPrimaryKey("dbo.University");
            DropPrimaryKey("dbo.Hobby");
            DropPrimaryKey("dbo.Language");
            DropPrimaryKey("dbo.Mark");
            DropPrimaryKey("dbo.SettingParameters");
            AlterColumn("dbo.Achivement", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Achivement", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Student", "FirstName", c => c.String(nullable: false));
            AlterColumn("dbo.Student", "LastName", c => c.String(nullable: false));
            AlterColumn("dbo.Parent", "FirstName", c => c.String(nullable: false));
            AlterColumn("dbo.Parent", "LastName", c => c.String(nullable: false));
            AlterColumn("dbo.Staff", "FirstName", c => c.String(nullable: false));
            AlterColumn("dbo.Staff", "LastName", c => c.String(nullable: false));
            AlterColumn("dbo.Address", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Country", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Country", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Contract", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Contract", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Invoice", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Invoice", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Payment", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Payment", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Session", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Session", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Class", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Class", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Specialty", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Specialty", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Faculty", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Faculty", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Group", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Group", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.University", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.University", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Hobby", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Hobby", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Language", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.Language", "Name", c => c.String(nullable: false));
            AlterColumn("dbo.Mark", "Id", c => c.Guid(nullable: false));
            AlterColumn("dbo.SettingParameters", "Id", c => c.Guid(nullable: false));
            AddPrimaryKey("dbo.Achivement", "Id");
            AddPrimaryKey("dbo.Address", "Id");
            AddPrimaryKey("dbo.Country", "Id");
            AddPrimaryKey("dbo.Contract", "Id");
            AddPrimaryKey("dbo.Invoice", "Id");
            AddPrimaryKey("dbo.Payment", "Id");
            AddPrimaryKey("dbo.Session", "Id");
            AddPrimaryKey("dbo.Class", "Id");
            AddPrimaryKey("dbo.Specialty", "Id");
            AddPrimaryKey("dbo.Faculty", "Id");
            AddPrimaryKey("dbo.Group", "Id");
            AddPrimaryKey("dbo.University", "Id");
            AddPrimaryKey("dbo.Hobby", "Id");
            AddPrimaryKey("dbo.Language", "Id");
            AddPrimaryKey("dbo.Mark", "Id");
            AddPrimaryKey("dbo.SettingParameters", "Id");
            AddForeignKey("dbo.Parent", "AddressId", "dbo.Address", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Student", "AddressId", "dbo.Address", "Id");
            AddForeignKey("dbo.Student", "LivingAddressId", "dbo.Address", "Id");
            AddForeignKey("dbo.Address", "CountryId", "dbo.Country", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Invoice", "ContractId", "dbo.Contract", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Payment", "InvoiceId", "dbo.Invoice", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Class", "SessionId", "dbo.Session", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Invoice", "SessionId", "dbo.Session", "Id");
            AddForeignKey("dbo.Mark", "ClassId", "dbo.Class", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Contract", "SpecialityId", "dbo.Specialty", "Id");
            AddForeignKey("dbo.Student", "SpecialityId", "dbo.Specialty", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Group", "FacultyId", "dbo.Faculty", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Specialty", "FacultyId", "dbo.Faculty", "Id");
            AddForeignKey("dbo.Student", "FacultyId", "dbo.Faculty", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Student", "GroupId", "dbo.Group", "Id");
            AddForeignKey("dbo.Faculty", "UniversityId", "dbo.University", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Contract", "UniversityId", "dbo.University", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Contract", "UniversityId", "dbo.University");
            DropForeignKey("dbo.Faculty", "UniversityId", "dbo.University");
            DropForeignKey("dbo.Student", "GroupId", "dbo.Group");
            DropForeignKey("dbo.Student", "FacultyId", "dbo.Faculty");
            DropForeignKey("dbo.Specialty", "FacultyId", "dbo.Faculty");
            DropForeignKey("dbo.Group", "FacultyId", "dbo.Faculty");
            DropForeignKey("dbo.Student", "SpecialityId", "dbo.Specialty");
            DropForeignKey("dbo.Contract", "SpecialityId", "dbo.Specialty");
            DropForeignKey("dbo.Mark", "ClassId", "dbo.Class");
            DropForeignKey("dbo.Invoice", "SessionId", "dbo.Session");
            DropForeignKey("dbo.Class", "SessionId", "dbo.Session");
            DropForeignKey("dbo.Payment", "InvoiceId", "dbo.Invoice");
            DropForeignKey("dbo.Invoice", "ContractId", "dbo.Contract");
            DropForeignKey("dbo.Address", "CountryId", "dbo.Country");
            DropForeignKey("dbo.Student", "LivingAddressId", "dbo.Address");
            DropForeignKey("dbo.Student", "AddressId", "dbo.Address");
            DropForeignKey("dbo.Parent", "AddressId", "dbo.Address");
            DropPrimaryKey("dbo.SettingParameters");
            DropPrimaryKey("dbo.Mark");
            DropPrimaryKey("dbo.Language");
            DropPrimaryKey("dbo.Hobby");
            DropPrimaryKey("dbo.University");
            DropPrimaryKey("dbo.Group");
            DropPrimaryKey("dbo.Faculty");
            DropPrimaryKey("dbo.Specialty");
            DropPrimaryKey("dbo.Class");
            DropPrimaryKey("dbo.Session");
            DropPrimaryKey("dbo.Payment");
            DropPrimaryKey("dbo.Invoice");
            DropPrimaryKey("dbo.Contract");
            DropPrimaryKey("dbo.Country");
            DropPrimaryKey("dbo.Address");
            DropPrimaryKey("dbo.Achivement");
            AlterColumn("dbo.SettingParameters", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Mark", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Language", "Name", c => c.String());
            AlterColumn("dbo.Language", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Hobby", "Name", c => c.String());
            AlterColumn("dbo.Hobby", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.University", "Name", c => c.String());
            AlterColumn("dbo.University", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Group", "Name", c => c.String());
            AlterColumn("dbo.Group", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Faculty", "Name", c => c.String());
            AlterColumn("dbo.Faculty", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Specialty", "Name", c => c.String());
            AlterColumn("dbo.Specialty", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Class", "Name", c => c.String());
            AlterColumn("dbo.Class", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Session", "Name", c => c.String());
            AlterColumn("dbo.Session", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Payment", "Name", c => c.String());
            AlterColumn("dbo.Payment", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Invoice", "Name", c => c.String());
            AlterColumn("dbo.Invoice", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Contract", "Name", c => c.String());
            AlterColumn("dbo.Contract", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Country", "Name", c => c.String());
            AlterColumn("dbo.Country", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Address", "Id", c => c.Guid(nullable: false, identity: true));
            AlterColumn("dbo.Staff", "LastName", c => c.String());
            AlterColumn("dbo.Staff", "FirstName", c => c.String());
            AlterColumn("dbo.Parent", "LastName", c => c.String());
            AlterColumn("dbo.Parent", "FirstName", c => c.String());
            AlterColumn("dbo.Student", "LastName", c => c.String());
            AlterColumn("dbo.Student", "FirstName", c => c.String());
            AlterColumn("dbo.Achivement", "Name", c => c.String());
            AlterColumn("dbo.Achivement", "Id", c => c.Guid(nullable: false, identity: true));
            AddPrimaryKey("dbo.SettingParameters", "Id");
            AddPrimaryKey("dbo.Mark", "Id");
            AddPrimaryKey("dbo.Language", "Id");
            AddPrimaryKey("dbo.Hobby", "Id");
            AddPrimaryKey("dbo.University", "Id");
            AddPrimaryKey("dbo.Group", "Id");
            AddPrimaryKey("dbo.Faculty", "Id");
            AddPrimaryKey("dbo.Specialty", "Id");
            AddPrimaryKey("dbo.Class", "Id");
            AddPrimaryKey("dbo.Session", "Id");
            AddPrimaryKey("dbo.Payment", "Id");
            AddPrimaryKey("dbo.Invoice", "Id");
            AddPrimaryKey("dbo.Contract", "Id");
            AddPrimaryKey("dbo.Country", "Id");
            AddPrimaryKey("dbo.Address", "Id");
            AddPrimaryKey("dbo.Achivement", "Id");
            AddForeignKey("dbo.Contract", "UniversityId", "dbo.University", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Faculty", "UniversityId", "dbo.University", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Student", "GroupId", "dbo.Group", "Id");
            AddForeignKey("dbo.Student", "FacultyId", "dbo.Faculty", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Specialty", "FacultyId", "dbo.Faculty", "Id");
            AddForeignKey("dbo.Group", "FacultyId", "dbo.Faculty", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Student", "SpecialityId", "dbo.Specialty", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Contract", "SpecialityId", "dbo.Specialty", "Id");
            AddForeignKey("dbo.Mark", "ClassId", "dbo.Class", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Invoice", "SessionId", "dbo.Session", "Id");
            AddForeignKey("dbo.Class", "SessionId", "dbo.Session", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Payment", "InvoiceId", "dbo.Invoice", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Invoice", "ContractId", "dbo.Contract", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Address", "CountryId", "dbo.Country", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Student", "LivingAddressId", "dbo.Address", "Id");
            AddForeignKey("dbo.Student", "AddressId", "dbo.Address", "Id");
            AddForeignKey("dbo.Parent", "AddressId", "dbo.Address", "Id", cascadeDelete: true);
        }
    }
}
