// <auto-generated />
namespace ARM.Data.CommonContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ClassAddFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClassAddFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201405041254105_ClassAddFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
