///////////////////////////////////////////////////////////
//  ARMValidatableViewModelBase.cs
//  Implementation of the Class ARMValidatableViewModelBase
//  Generated by Enterprise Architect
//  Created on:      30-Mar-2014 8:12:16 PM
///////////////////////////////////////////////////////////

using ARM.Core.Interfaces;

namespace ARM.Infrastructure.MVVM
{
    public class ARMValidatableViewModelBase : ARMDataViewModelBase, IARMValidatableViewModel
    {
        private ARM.Core.Interfaces.IARMValidationAdaptor _validationAdaptor;

        ///
        /// <param name="businessObject"></param>
        /// <param name="view"></param>
        protected ARMValidatableViewModelBase(object businessObject, IARMView view) : base(businessObject,view)
        {
        }

        public IARMView View
        {
            get;
            set;
        }

        public void InitializeValidationRules()
        {
        }

        public object DataObject()
        {
            return null;
        }

        public string this[string columnName]
        {
            get { throw new System.NotImplementedException(); }
        }

        public string Error { get; private set; }
    }//end ARMValidatableViewModelBase
}//end namespace MVVM