///////////////////////////////////////////////////////////
//  ARMWorkspaceViewModelBase.cs
//  Implementation of the Class ARMWorkspaceViewModelBase
//  Generated by Enterprise Architect
//  Created on:      31-Mar-2014 12:33:20 AM
///////////////////////////////////////////////////////////

using System;
using System.Windows.Input;
using ARM.Core.Interfaces;
using ARM.Core.MVVM;
using Microsoft.Practices.Prism.Commands;
using Microsoft.Practices.Prism.Events;
using Microsoft.Practices.Prism.Regions;
using Microsoft.Practices.Unity;

namespace ARM.Infrastructure.MVVM
{
    public class ARMWorkspaceViewModelBase : ARMViewModelBase,IARMWorkspaceViewModel
    {

#region [needs]
        private ICommand _closeCommand;
        protected readonly IRegionManager RegionManager;
        protected readonly IUnityContainer UnityContainer;
        protected readonly IEventAggregator EventAggregator;
#endregion


        public class CloseAbort
        {
            public bool Handled { get; set; }
        }

        public ARMWorkspaceViewModelBase(IRegionManager regionManager,IUnityContainer unityContainer,IEventAggregator eventAggregator, IARMView view)
            : base(view)
        {
            RegionManager = regionManager;
            UnityContainer = unityContainer;
            EventAggregator = eventAggregator;
        }

        
        public ICommand CloseCommand
        {
            get
            {
                if (_closeCommand == null)
                {
                    _closeCommand = new DelegateCommand(OnClose);
                }
                return _closeCommand;
            }
        }

        public event EventHandler RequestClose;

        protected virtual void Closing(CloseAbort args)
        {   
        }

        protected virtual void Closed(){}

        private void OnClose()
        {
            var args = new CloseAbort() {Handled = false};
            Closing(args);

            EventHandler temp = RequestClose;
            if (temp != null && !args.Handled)
                temp(this, EventArgs.Empty);
            Closed();
        }

    }//end ARMWorkspaceViewModelBase
}//end namespace MVVM