///////////////////////////////////////////////////////////
//  MainModule.cs
//  Implementation of the Class MainModule
//  Generated by Enterprise Architect
//  Created on:      31-Mar-2014 11:50:26 PM
///////////////////////////////////////////////////////////

using ARM.Core.Interfaces;
using ARM.Core.Module;
using ARM.Infrastructure.Interfaces.Grid;
using ARM.Module.Interfaces;
using ARM.Module.Interfaces.View;
using ARM.Module.View;
using ARM.Module.View.Grid;
using ARM.Module.ViewModel.Main;
using Microsoft.Practices.Prism.Events;
using Microsoft.Practices.Prism.Modularity;
using Microsoft.Practices.Prism.Regions;
using Microsoft.Practices.Unity;
using ARM.Infrastructure.Region;
using Unity.AutoRegistration;

namespace ARM.Module
{
    public class MainModule : ARMBaseModule
    {
        public MainModule(IRegionManager regionManager, IUnityContainer unityContainer, IEventAggregator eventAggregator)
            : base(regionManager, unityContainer, eventAggregator)
        {
        }

        protected override void RegistreInterfaces()
        {
            base.RegistreInterfaces();
            //registre view
            UnityContainer.RegisterType<IARMMainWorkspaceView, ARMMainWorkspaceView>();
            UnityContainer.RegisterType<IARMMainMenuView, ARMMenuView>();
            UnityContainer.RegisterType<IARMMainStatusBarView, ARMStatusBarView>();
            UnityContainer.RegisterType<IARMMainToolboxView, ARMToolboxView>();
            //register view model
            UnityContainer.RegisterType<IARMMainWorkspaceViewModel, ARMMainWorkspaceViewModel>(new ContainerControlledLifetimeManager());
            UnityContainer.RegisterType<IARMMainMenuViewModel, ARMMainMenuViewModel>();
            UnityContainer.RegisterType<IARMMainStatusBarViewModel, ARMMainStatusBarViewModel>();
            UnityContainer.RegisterType<IARMMainToolboxViewModel, ARMMainToolboxViewModel>();

            //additional
            UnityContainer.RegisterType<IARMGridView, ARMGridView>();

            UnityContainer.ConfigureAutoRegistration()
                .ExcludeSystemAssemblies()
                .Include(type => type.ImplementsOpenGeneric(typeof(IARMGridViewModel<>)), Then.Register().UsingPerCallMode())
                    .ApplyAutoRegistration();

        }

        protected override void InjectViews()
        {
            base.InjectViews();
            IARMMainWorkspaceViewModel mainViewModel = UnityContainer.Resolve<IARMMainWorkspaceViewModel>();
            IRegion region = RegionManager.Regions[ARMMainRegionNames.WORKSPACE_REGION];
            region.Add(mainViewModel.View);
            region = RegionManager.Regions[ARMMainRegionNames.MENU_REGION];
            region.Add(mainViewModel.MenuView);
            region = RegionManager.Regions[ARMMainRegionNames.STATUSBAR_REGION];
            region.Add(mainViewModel.StatusBarView);
            region = RegionManager.Regions[ARMMainRegionNames.TOOLBOX_REGION];
            region.Add(mainViewModel.ToolboxView);
        }
    }//end MainModule
}//end namespace ARM.Module