///////////////////////////////////////////////////////////
//  BaseContext.cs
//  Implementation of the Class BaseContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:38 PM
///////////////////////////////////////////////////////////


using System.Data.Entity;
using ARM.Data.Layer.Interfaces;
namespace ARM.Data.Layer.Context {
	public class BaseContext<T> : DbContext, IContext<T> where T : class
	{

		public BaseContext()
            : base("MainDatabase")
        {
		}

		~BaseContext(){

		}

		public void Save(){

		}

		public DbSet<T> Items{
			get;
			set;
		}

	}//end BaseContext

}//end namespace Context