///////////////////////////////////////////////////////////
//  BaseContext.cs
//  Implementation of the Class BaseContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:38 PM
///////////////////////////////////////////////////////////

using System.Data.Entity;

namespace ARM.Data.Layer.Context
{
    public class BaseContext : DbContext
    {
        public BaseContext()
            : base("MainDatabase")
        {
        }

        public void Save()
        {
        }
    }//end BaseContext
}//end namespace Context