///////////////////////////////////////////////////////////
//  IFacultyDal.cs
//  Implementation of the Interface IFacultyDal
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:41 PM
///////////////////////////////////////////////////////////




using ARM.Data.Layer.Interfaces;
namespace ARM.Data.Interfaces.Faculty {
    public interface IFacultyDal : IDal<Models.Faculty>
    {

	}//end IFacultyDal

}//end namespace Faculty