///////////////////////////////////////////////////////////
//  IFacultyContext.cs
//  Implementation of the Interface IFacultyContext
//  Generated by Enterprise Architect
//  Created on:      29-Mar-2014 5:16:41 PM
///////////////////////////////////////////////////////////

using ARM.Data.Layer.Interfaces;

namespace ARM.Data.Interfaces.Faculty
{
    public interface IFacultyContext : IContext<Models.Faculty>
    {
    }//end IFacultyContext
}//end namespace Faculty